# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib razer, .registration = TRUE
NULL

#' Named integer vector of epidemic compartment state codes.
#'
#' Returns `c(S=0L, E=1L, I=2L, R=3L, M=4L, D=-1L)`. Use these constants to set
#' and test the `state` property on a people frame. `M` is maternal immunity
#' (newborns protected by maternal antibodies, waning to `S`); `D` is deceased.
#'
#' @return Named integer vector with elements S, E, I, R, M, D.
#' @export
laser_states <- function() .Call(wrap__laser_states)

#' Set the global random seed, making subsequent razer runs reproducible.
#'
#' After `set_seed(s)`, every kernel's randomness is a deterministic function of `s` and
#' the order of kernel calls — identical on every run and every machine, regardless of
#' CPU/thread count. Call it once at the start of a script. `unset_seed()` reverts to a
#' fresh (entropy-seeded) RNG.
#'
#' @param seed A finite, non-negative number (used as a 64-bit seed).
#' @return `NULL`, invisibly.
#' @examples
#' set_seed(42)
#' @export
set_seed <- function(seed) .Call(wrap__set_seed, seed)

#' Revert to a non-reproducible, entropy-seeded RNG (undo [set_seed()]).
#'
#' @return `NULL`, invisibly.
#' @export
unset_seed <- function() .Call(wrap__unset_seed)

#' Create a normal (Gaussian) distribution.
#'
#' The second argument is the **variance** (σ²), not the standard deviation, to
#' match the way variance is usually quoted in statistical models. The standard
#' deviation passed to the underlying sampler is `sqrt(variance)`.
#'
#' @param mean      Mean (μ) of the distribution.
#' @param variance  Variance (σ²); must be non-negative.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_normal(7, 4)   # mean 7, variance 4 (sd 2)
#' d$sample_one()
#' @export
dist_normal <- function(mean, variance) .Call(wrap__dist_normal, mean, variance)

#' Create a degenerate (constant) distribution that always returns `value`.
#'
#' Use this as a fixed-duration drop-in wherever a `Distribution` is required —
#' e.g. a deterministic infectious period of exactly `value` ticks.
#'
#' @param value The constant value returned by every draw.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_constant(10)   # always 10
#' d$sample_one()
#' @export
dist_constant <- function(value) .Call(wrap__dist_constant, value)

#' Create a continuous uniform distribution on the half-open interval [low, high).
#'
#' Every value in `[low, high)` is equally likely. The mean is `(low + high) / 2`.
#'
#' @param low   Inclusive lower bound.
#' @param high  Exclusive upper bound; must be strictly greater than `low`.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_uniform(3, 8)   # values in [3, 8), mean 5.5
#' d$sample_one()
#' @export
dist_uniform <- function(low, high) .Call(wrap__dist_uniform, low, high)

#' Create a gamma distribution parameterized by shape and scale.
#'
#' Uses the shape–scale (k, θ) parameterization: the mean is `shape * scale` and
#' the variance is `shape * scale^2`. Draws are strictly positive, which makes the
#' gamma a natural choice for right-skewed, always-positive durations.
#'
#' @param shape  Shape parameter k; must be finite and positive.
#' @param scale  Scale parameter θ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_gamma(2, 3)   # mean 6, variance 18
#' d$sample_one()
#' @export
dist_gamma <- function(shape, scale) .Call(wrap__dist_gamma, shape, scale)

#' Create a Poisson distribution with rate (mean) `lambda`.
#'
#' Draws are non-negative integer counts (returned as doubles) with mean and
#' variance both equal to `lambda`. Useful for count-valued durations.
#'
#' @param lambda  Rate / mean λ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_poisson(5)   # mean 5, integer-valued draws
#' d$sample_one()
#' @export
dist_poisson <- function(lambda) .Call(wrap__dist_poisson, lambda)

#' Create a beta distribution on the open interval (0, 1).
#'
#' Parameterized by the two positive shape parameters α and β. The mean is
#' `alpha / (alpha + beta)`.
#'
#' @param alpha  First shape parameter (α); must be finite and positive.
#' @param beta   Second shape parameter (β); must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_beta(2, 5)   # mean 2/7 ≈ 0.286, support (0, 1)
#' d$sample_one()
#' @export
dist_beta <- function(alpha, beta) .Call(wrap__dist_beta, alpha, beta)

#' Create an exponential distribution with rate `rate`.
#'
#' Draws are strictly positive with mean `1 / rate` and variance `1 / rate^2`.
#'
#' @param rate  Rate parameter λ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_exp(0.5)   # mean 2
#' d$sample_one()
#' @export
dist_exp <- function(rate) .Call(wrap__dist_exp, rate)

#' Create a logistic distribution with the given location and scale.
#'
#' Symmetric about `location` (its mean and median); the variance is
#' `scale^2 * pi^2 / 3`.
#'
#' @param location  Location parameter μ (the mean); must be finite.
#' @param scale     Scale parameter s; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_logistic(4, 2)   # mean 4
#' d$sample_one()
#' @export
dist_logistic <- function(location, scale) .Call(wrap__dist_logistic, location, scale)

#' Create a log-normal distribution.
#'
#' A variable whose natural logarithm is `Normal(meanlog, sdlog)`. Draws are
#' strictly positive. The median is `exp(meanlog)` and the mean is
#' `exp(meanlog + sdlog^2 / 2)`. `meanlog` and `sdlog` are the log-space
#' parameters, matching R's `qlnorm(p, meanlog, sdlog)`.
#'
#' @param meanlog  Mean of the underlying normal (in log space); must be finite.
#' @param sdlog    Standard deviation of the underlying normal; must be finite
#'   and non-negative.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_lognormal(0, 0.5)   # median 1
#' d$sample_one()
#' @export
dist_lognormal <- function(meanlog, sdlog) .Call(wrap__dist_lognormal, meanlog, sdlog)

#' Great-circle distance matrix between geographic points.
#'
#' Ports laser-core's `distance` (all-pairs case): given the latitudes and
#' longitudes of `N` points in decimal degrees, returns the symmetric `N × N`
#' matrix whose `[i, j]` entry is the haversine great-circle distance, in
#' **kilometres**, between point `i` and point `j`. The diagonal is zero.
#'
#' The haversine formula (see <https://en.wikipedia.org/wiki/Haversine_formula>)
#' is evaluated with a mean Earth radius of 6371 km, matching laser-core.
#'
#' @param latitude  Numeric vector of latitudes in decimal degrees, in `[-90, 90]`.
#' @param longitude Numeric vector of longitudes in decimal degrees, in `[-180, 180]`.
#'   Must be the same length as `latitude`.
#' @return An `N × N` numeric matrix of pairwise distances in kilometres
#'   (symmetric, zero diagonal), where `N` is the number of points.
#' @examples
#' # London and Paris, ~344 km apart:
#' d <- distances(c(51.5074, 48.8566), c(-0.1278, 2.3522))
#' d[1, 2]
#' @export
distances <- function(latitude, longitude) .Call(wrap__distances, latitude, longitude)

#' Gravity migration-network model.
#'
#' `network[i, j] = k * pops[i]^a * pops[j]^b / distance[i, j]^c`, with a zero
#' diagonal (no self-migration). Port of laser-core's `gravity`.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix (e.g. from
#'   [distances()]).
#' @param k Scaling constant for the overall flow magnitude (non-negative).
#' @param a Exponent on the origin population.
#' @param b Exponent on the destination population.
#' @param c Exponent on the distance (larger `c` = stronger distance decay).
#' @return An `N × N` numeric matrix; `[i, j]` is the migration weight from node
#'   i to node j.
#' @export
gravity <- function(pops, distances, k, a, b, c) .Call(wrap__gravity, pops, distances, k, a, b, c)

#' Radiation migration-network model (Simini et al., Nature 2012).
#'
#' For each source `i`, destinations are ranked by distance and the weight to
#' destination `j` is
#' `k * p_i * p_j / (p_i + s) / (p_i + p_j + s)`, where `s` is the total
#' population of all nodes as close or closer to `i` than `j` (excluding the home
#' population `p_i` when `include_home = FALSE`). Port of laser-core's
#' `radiation`. The diagonal is 0.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix.
#' @param k Scaling constant for the flow magnitude (non-negative).
#' @param include_home Logical; whether the home (source) population is included
#'   in the "as close or closer" cumulative sum.
#' @return An `N × N` numeric migration-weight matrix (generally not symmetric).
#' @export
radiation <- function(pops, distances, k, include_home) .Call(wrap__radiation, pops, distances, k, include_home)

#' Competing-destinations migration model (Fotheringham, 1984).
#'
#' Starts from the [gravity()] weights and multiplies each `[i, j]` by an
#' accessibility term `(Σ_k p_k^b / d_jk^c)^delta`, summed over competing
#' destinations `k ∉ {i, j}`. Port of laser-core's `competing_destinations`. The
#' diagonal is 0.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix.
#' @param k Scaling constant for the flow magnitude (non-negative).
#' @param a Exponent on the origin population (gravity term).
#' @param b Exponent on the destination population (gravity and competition terms).
#' @param c Exponent on distance (gravity and competition terms).
#' @param delta Exponent on the competing-destinations accessibility term.
#' @return An `N × N` numeric migration-weight matrix (generally not symmetric).
#' @export
competing_destinations <- function(pops, distances, k, a, b, c, delta) .Call(wrap__competing_destinations, pops, distances, k, a, b, c, delta)

#' Stouffer's intervening-opportunities migration model (Stouffer, 1940).
#'
#' For each source `i` and destination `j`,
#' `network[i, j] = k * p_i^a * (p_j / s)^b`, where `s` is the cumulative
#' population as close or closer to `i` than `j` (excluding the home population
#' when `include_home = FALSE`); the nearest node (the source) gets weight 0.
#' Port of laser-core's `stouffer`. The diagonal is 0.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix.
#' @param k Scaling constant for the flow magnitude (non-negative).
#' @param a Exponent on the origin population.
#' @param b Exponent on the destination/cumulative-population ratio.
#' @param include_home Logical; whether the home population is included in the
#'   cumulative sum.
#' @return An `N × N` numeric migration-weight matrix (generally not symmetric).
#' @export
stouffer <- function(pops, distances, k, a, b, include_home) .Call(wrap__stouffer, pops, distances, k, a, b, include_home)

#' Cap each row sum of a network matrix at `max_rowsum`.
#'
#' Rows whose total exceeds `max_rowsum` are scaled down proportionally so they
#' sum to exactly `max_rowsum`; smaller rows are left unchanged. Port of
#' laser-core's `row_normalizer`. Useful to bound the fraction of a node's force
#' of infection that is exported before passing the matrix as the transmission
#' `network`.
#'
#' @param network    A square non-negative numeric matrix.
#' @param max_rowsum Maximum allowed row sum, in `[0, 1]`.
#' @return The row-capped matrix, same shape as `network`.
#' @export
row_normalizer <- function(network, max_rowsum) .Call(wrap__row_normalizer, network, max_rowsum)

#' Allocate a fresh, zero-filled property array of a given type and length.
#'
#' Returns an opaque [Column] handle backed by a Rust-owned buffer. Choose the
#' narrowest type that fits the data to minimize memory (e.g. `"u8"` for a small
#' set of disease-state codes).
#'
#' @param dtype Element type, one of `"i8"`, `"u8"`, `"i16"`, `"u16"`, `"i32"`,
#'   `"u32"`, `"f32"`, `"f64"` (aliases: `"int8"`, `"uint8"`/`"raw"`, …,
#'   `"integer"` = i32, `"double"`/`"real"` = f64, `"single"` = f32).
#' @param count Array length (number of elements); a non-negative integer.
#' @return A [Column] object whose elements are all zero.
#' @examples
#' state <- allocate_scalar("u8", 5L)
#' state$dtype()    # "u8"
#' state$length()   # 5
#' state$values()   # 0 0 0 0 0
#' @export
allocate_scalar <- function(dtype, count) .Call(wrap__allocate_scalar, dtype, count)

#' Allocate a fresh, zero-filled 2-D property array (a per-slot report buffer).
#'
#' Returns an opaque [Column] of `n_slices * slice_len` elements laid out
#' SLICE-MAJOR (row-major): `n_slices` slices, each a contiguous run of `slice_len`
#' elements. Slice `s` is the block `s*slice_len .. (s+1)*slice_len`, so indexing
#' the FIRST dimension yields a contiguous array. The conventional use is a
#' time-series report with the **first dimension time and the second node** —
#' `allocate_vector(dtype, n_ticks, n_nodes)` — so each tick's per-node values are
#' contiguous (cache-friendly for the step kernels that fill one tick at a time).
#' `$values()` reads it back as an `n_slices × slice_len` (e.g. `n_ticks × n_nodes`)
#' R matrix, so row `t` is tick `t`'s vector.
#'
#' @param dtype     Element type (see [allocate_scalar()] for the accepted names).
#' @param n_slices  Number of slices — the first/outer dimension (e.g. the tick
#'   count). A non-negative integer.
#' @param slice_len Contiguous length of each slice — the inner dimension (e.g. the
#'   node count). A non-negative integer.
#' @return A [Column] of shape `n_slices × slice_len`, all elements zero.
#' @examples
#' recoveries <- allocate_vector("u32", 4L, 3L)   # 4 ticks x 3 nodes
#' dim(recoveries$values())                        # 4 3
#' @export
allocate_vector <- function(dtype, n_slices, slice_len) .Call(wrap__allocate_vector, dtype, n_slices, slice_len)

#' Carry a per-node counter forward one tick: copy column `tick` onto `tick + 1`.
#'
#' For a 2-D report [Column] (e.g. `n_ticks+1 × n_nodes`), copies the contiguous
#' slice for `tick` onto the slice for `tick + 1`. This seeds the next tick with the
#' current counts so a dynamics kernel can then update it in place — keeping the
#' census invariant `count[t+1] = count[t] ± delta`. Call it once per state that
#' must persist across ticks (e.g. S, I, R for an SIR model; add E for SEIR, or a
#' user-defined "V" vaccinated count). Works for any element type.
#'
#' @param counter A 2-D Column to carry forward.
#' @param tick    0-based source tick; column `tick` is copied onto column `tick+1`.
#' @return `NULL` (invisibly); `counter` is modified in place.
#' @examples
#' counts <- allocate_vector("i32", 3L, 2L)   # 3 ticks x 2 nodes
#' counts$set(c(5L, 7L, 0L, 0L, 0L, 0L))      # tick 0 = (5, 7)
#' carry_forward(counts, 0L)
#' counts$values()[2L, ]                       # 5 7  (carried to tick 1)
#' @export
carry_forward <- function(counter, tick) .Call(wrap__carry_forward, counter, tick)

#' Count occurrences of each value, NumPy `bincount`-style, into a buffer.
#'
#' For each bin `b` in `0..nbins`, computes how many elements of `values` equal
#' `b` and writes that into `counts[b]`. `values` must be an integer-typed
#' [Column] whose elements lie in `0..nbins` (they are used as bin indices);
#' `counts` is a numeric [Column] and the result is written into **slice `slot`**
#' of it — the `nbins` entries `slot*slice_len .. slot*slice_len + nbins` —
#' overwriting them while leaving the rest of the slice (and other slices)
#' untouched. For a scalar `counts` (shape `(1, n)`) the only slice is `slot = 0`,
#' the whole vector; for a 2-D report (e.g. `(n_ticks, n_nodes)`) `slot` selects a
#' tick's row. The work is parallelized with private per-thread histograms, so
#' there are no write collisions.
#'
#' @param values An integer-typed `Column` of bin indices (`i8`..`u32`).
#' @param nbins  Number of bins; a non-negative integer `<= counts`'s slice length.
#' @param counts A numeric `Column` that receives the counts (modified in place).
#' @param slot   Which slice of `counts` to write; a non-negative integer
#'   `< counts`'s slice count. Defaults to `0` (the whole vector for a scalar
#'   `counts`, or the first tick of a report). `@param` is optional.
#' @return `NULL` (invisibly); the result is written into `counts`.
#' @examples
#' values <- allocate_scalar("u16", 6L)
#' values$set(c(0, 1, 1, 2, 2, 2))
#' counts <- allocate_scalar("i32", 3L)
#' bincount(values, 3L, counts)
#' counts$values()   # 1 2 3
#' @noRd
bincount_impl <- function(values, nbins, counts, slot) .Call(wrap__bincount_impl, values, nbins, counts, slot)

#' Weighted bincount: sum each element's weight into its bin (NumPy
#' `bincount(values, weights=...)`).
#'
#' For each bin `b` in `0..nbins`, computes `sum of weights[i] over all i with
#' values[i] == b` and writes it into **slice `slot`** of `counts` (the entries
#' `slot*slice_len .. slot*slice_len + nbins`), overwriting them. `values` must be
#' an integer-typed [Column] of bin indices in `0..nbins`; `weights` is any numeric
#' [Column] (signed, unsigned, or floating point) the SAME length as `values`;
#' `counts` is a numeric [Column] whose slice length is `>= nbins`. For a scalar
#' `counts` the only slice is `slot = 0` (the whole vector); for a 2-D report
#' `slot` selects a tick's row. Parallelized with private per-thread accumulators,
#' so there are no write collisions.
#'
#' @param values  An integer-typed `Column` of bin indices (`i8`..`u32`).
#' @param weights A numeric `Column` (any type), the same length as `values`.
#' @param nbins   Number of bins; a non-negative integer `<= counts`'s slice length.
#' @param counts  A numeric `Column` that receives the sums (modified in place).
#' @param slot    Which slice of `counts` to write; a non-negative integer
#'   `< counts`'s slice count. Defaults to `0`.
#' @return `NULL` (invisibly); the result is written into `counts`.
#' @examples
#' values  <- allocate_scalar("u16", 5L); values$set(c(0, 0, 1, 2, 2))
#' weights <- allocate_scalar("f64", 5L); weights$set(c(1.5, 2.5, 4, 1, 3))
#' counts  <- allocate_scalar("f64", 3L)
#' bincount_wt(values, weights, 3L, counts)
#' counts$values()   # 4 4 4
#' @noRd
bincount_wt_impl <- function(values, weights, nbins, counts, slot) .Call(wrap__bincount_wt_impl, values, weights, nbins, counts, slot)

#' Count, per group, the agents whose property satisfies a comparison (filtered bincount).
#'
#' For each group `g` in `0..n_groups`, counts how many of the first `count` agents both
#' have `group[i] == g` AND satisfy `prop[i] <op> value`, and writes the totals into
#' **slice `slot`** of `counts` (entries `slot*slice_len .. slot*slice_len + n_groups`),
#' overwriting them. This is `bincount` restricted to a predicate and to the live prefix
#' `0..count` — e.g. with `group = nodeid`, `prop = state`, `op = "eq"`, `value = E` it
#' tallies the exposed by node; with `prop = dob`, `op = "gt"`, `value = tick - 5*365` it
#' tallies the under-fives by node (since `dob = -age`). `group` must be an integer-typed
#' [Column] of indices in `0..n_groups`; `prop` is any numeric [Column] (compared as
#' `f64`); `counts` is numeric with slice length `>= n_groups`. Parallelized with private
#' per-thread histograms, so there are no write collisions.
#'
#' @param group    An integer-typed `Column` of group indices (`i8`..`u32`), e.g. nodeid.
#' @param n_groups Number of groups; a non-negative integer `<= counts`'s slice length.
#' @param prop     A numeric `Column` (any type) holding the per-agent property to test.
#' @param op       Comparison: one of `"eq"`, `"ne"`, `"lt"`, `"le"`, `"gt"`, `"ge"`.
#' @param value    The threshold the property is compared against (a double).
#' @param count    How many leading agents to scan (the active count); `<= group`/`prop`
#'   length.
#' @param counts   A numeric `Column` that receives the per-group totals (modified in place).
#' @param slot     Which slice of `counts` to write; a non-negative integer
#'   `< counts`'s slice count. Defaults to `0`.
#' @return `NULL` (invisibly); the result is written into `counts`.
#' @noRd
bincount_where_impl <- function(group, n_groups, prop, op, value, count, counts, slot) .Call(wrap__bincount_where_impl, group, n_groups, prop, op, value, count, counts, slot)

#' Weighted, predicate-filtered bincount: sum a weight per group over matching agents.
#'
#' The weighted twin of [bincount_where()]: for each group `g` in `0..n_groups`, sums
#' `weights[i]` over the first `count` agents that both have `group[i] == g` AND satisfy
#' `prop[i] <op> value`, writing the per-group sums into **slice `slot`** of `counts`.
#' Use it for predicate-filtered weighted aggregates by node — e.g. total infectiousness
#' of symptomatic agents per node, or person-days under five — in one parallel pass with
#' no copy of `prop` or `weights` into R. `group` must be integer-typed (`i8`..`u32`);
#' `prop` and `weights` are any numeric [Column]s; `counts` is numeric with slice length
#' `>= n_groups`.
#'
#' @param group    An integer-typed `Column` of group indices (`i8`..`u32`), e.g. nodeid.
#' @param n_groups Number of groups; a non-negative integer `<= counts`'s slice length.
#' @param prop     A numeric `Column` holding the per-agent property to test.
#' @param op       Comparison: one of `"eq"`, `"ne"`, `"lt"`, `"le"`, `"gt"`, `"ge"`.
#' @param value    The threshold the property is compared against (a double).
#' @param weights  A numeric `Column` (any type) of per-agent weights to sum.
#' @param count    How many leading agents to scan (the active count).
#' @param counts   A numeric `Column` that receives the per-group sums (modified in place).
#' @param slot     Which slice of `counts` to write; defaults to `0`.
#' @return `NULL` (invisibly); the result is written into `counts`.
#' @noRd
bincount_where_wt_impl <- function(group, n_groups, prop, op, value, weights, count, counts, slot) .Call(wrap__bincount_where_wt_impl, group, n_groups, prop, op, value, weights, count, counts, slot)

#' Compute the per-node force of infection (FOI) for one tick.
#'
#' Computes the frequency-dependent, network-redistributed FOI **rate** into column
#' `tick` of `foi`. The local rate per node is
#' `r[k] = beta[k] * seasonality[k] * infected[k] / population[k]`, redistributed as
#' `foi[k] = r[k] * (1 - sum_j W[k, j]) + sum_i r[i] * W[i, k]`. The transmission
#' kernels turn this rate into a per-tick probability `1 - exp(-foi)`.
#'
#' Index conventions: `infected` and `population` are census buffers read at the
#' **start-of-interval** column `tick` (the settled census recorded for tick `tick`, the
#' infectious count and population at the start of the interval `tick → tick+1`); `beta`
#' and `seasonality` are exogenous modifier grids read at the interval column `tick`; the
#' result is written to `foi[tick]`.
#'
#' **Ordering and the effective infectious period.** Because `calc_foi` reads the SETTLED
#' census at column `tick` — not the working column `tick+1` that this interval's step
#' kernel and transmission build — its result does NOT depend on where the step kernel
#' runs. That lets every model use ONE ordering: `carry_forward → step → calc_foi →
#' transmission`, with `calc_foi` placed immediately before `transmission`. Under it an
#' agent contributes to the FOI on exactly the `D` census columns it occupies (it enters
#' `I` at column `entry+1` via either the step kernel's E→I or transmission's S→I, and
#' recovers `D` columns later), so the realized basic reproduction number is the full
#' `R0 = beta * D` — for both direct S→I (SIR) and SEIR-style entry, with no `beta*(D-1)`
#' artifact and no per-family special-casing.
#'
#' @param infected   Infectious-count census Column (`nodes$I`), `slice_len == n_nodes`.
#' @param population Per-node population census Column (`nodes$N`); the FOI denominator.
#' @param beta       Transmission-coefficient grid (`n_ticks x n_nodes`, from [values_map()]).
#' @param seasonality Seasonal-modifier grid (`n_ticks x n_nodes`, from [values_map()]).
#' @param network    An `n_nodes x n_nodes` numeric coupling matrix.
#' @param foi        A 2-D f64 Column (`(n_ticks-1) x n_nodes`); column `tick` is overwritten.
#' @param tick       0-based tick index: reads `beta[tick]`/`seasonality[tick]` and
#'   `infected[tick]`/`population[tick]` (the start-of-interval census), writes `foi[tick]`.
#' @return `NULL` (invisibly); the result is written into `foi`.
#' @export
calc_foi <- function(infected, population, beta, seasonality, network, foi, tick) .Call(wrap__calc_foi, infected, population, beta, seasonality, network, foi, tick)

#' Stochastic transmission S→`to_state`, returning new infections per node.
#'
#' Converts column `tick` of `foi` to a per-node probability `1 - exp(-foi)` (once per
#' node), then for each susceptible agent moves it — with that probability — into
#' `to_state` (`E` or `I`), setting its u16 `timer` from `duration` (the incubation or
#' infectious period). The node census is NOT touched: the per-node count of new
#' infections is RETURNED, and the caller applies the `S` ↓ / `to_state` ↑ delta and
#' records incidence as its model requires (it knows whether this is S→E or S→I).
#'
#' @param state    Per-agent `u8` state Column (mutated).
#' @param timer    Per-agent `u16` timer Column (mutated; set from `duration`).
#' @param nodeid   Per-agent `u16` 0-based node-id Column.
#' @param count    Number of active agents to process.
#' @param foi      `n_ticks x n_nodes` f64 FOI Column (from [calc_foi()]); column `tick` read.
#' @param tick     0-based tick index.
#' @param to_state State code new infections enter (`laser_states()[["E"]]` or `[["I"]]`).
#' @param duration A Distribution from which the receiving state's timer is drawn.
#' @return An integer vector of new infections per node (length `n_nodes`).
#' @export
transmission <- function(state, timer, nodeid, count, foi, tick, to_state, duration) .Call(wrap__transmission, state, timer, nodeid, count, foi, tick, to_state, duration)

#' Stochastic transmission S→I into an ABSORBING `I` (the SI model), returning new
#' infections per node.
#'
#' Like [transmission()] but the agent enters `I` permanently — no `timer` is set (`I`
#' is terminal in SI). Returns the per-node count of new infections; the caller applies
#' the `S` ↓ / `I` ↑ delta.
#'
#' @param state    Per-agent `u8` state Column (mutated; S→I).
#' @param nodeid   Per-agent `u16` 0-based node-id Column.
#' @param count    Number of active agents to process.
#' @param foi      `n_ticks x n_nodes` f64 FOI Column; column `tick` read.
#' @param tick     0-based tick index.
#' @return An integer vector of new infections per node (length `n_nodes`).
#' @export
transmission_si <- function(state, nodeid, count, foi, tick) .Call(wrap__transmission_si, state, nodeid, count, foi, tick)

#' Advance M→S (maternal waning) and E→I (incubation) for one tick — SI / SEI.
#'
#' `I` is terminal (no exit). Returns `list(waned, onset)` of per-node counts.
#'
#' @param state   Per-agent `u8` state Column (mutated).
#' @param timer   Per-agent `u16` timer Column (mutated; E→I draws an infectious timer).
#' @param nodeid  Per-agent `u16` 0-based node-id Column.
#' @param count   Number of active agents to process.
#' @param n_nodes Number of nodes (the length of each returned vector).
#' @param inf_duration A Distribution for the infectious period set on E→I.
#' @return `list(waned = integer[n_nodes], onset = integer[n_nodes])`.
#' @export
step_si <- function(state, timer, nodeid, count, n_nodes, inf_duration) .Call(wrap__step_si, state, timer, nodeid, count, n_nodes, inf_duration)

#' Advance M→S, E→I, and I→`absorbing_state` for one tick — SIS / SIR / SEIS / SEIR.
#'
#' `absorbing_state` is the untimed destination of the infectious period: `S` (SIS/SEIS)
#' or `R` (SIR/SEIR). Returns `list(waned, onset, cleared)` of per-node counts (`cleared`
#' is the I→`absorbing_state` flow).
#'
#' @param state,timer,nodeid,count,n_nodes  As in [step_si()].
#' @param inf_duration   A Distribution for the infectious period set on E→I.
#' @param absorbing_state State code I clears to (`laser_states()[["S"]]` or `[["R"]]`).
#' @return `list(waned, onset, cleared)` of `integer[n_nodes]`.
#' @export
step_sir <- function(state, timer, nodeid, count, n_nodes, inf_duration, absorbing_state) .Call(wrap__step_sir, state, timer, nodeid, count, n_nodes, inf_duration, absorbing_state)

#' Advance M→S, E→I, I→R (with waning immunity), and R→S for one tick — SIRS / SEIRS.
#'
#' On I→R a fresh immunity timer is drawn from `imm_duration`; R→S fires when it expires.
#' Returns `list(waned, onset, recovered, waned_r)` of per-node counts.
#'
#' @param state,timer,nodeid,count,n_nodes  As in [step_si()].
#' @param inf_duration A Distribution for the infectious period set on E→I.
#' @param imm_duration A Distribution for the immunity period set on I→R.
#' @return `list(waned, onset, recovered, waned_r)` of `integer[n_nodes]`.
#' @export
step_sirs <- function(state, timer, nodeid, count, n_nodes, inf_duration, imm_duration) .Call(wrap__step_sirs, state, timer, nodeid, count, n_nodes, inf_duration, imm_duration)

#' Generic timed transition `from_state -> to_state` into an UNTIMED destination.
#'
#' For each agent in `from_state`, decrements its u16 `timer`; on expiry the agent moves
#' to `to_state` (timer left at 0). Returns the per-node count of transitions. Compose
#' these (downstream-first) to build models beyond the named menagerie; apply the counts
#' with `move_count`. Generalizes the M→S / R→S / I→{S,R} legs.
#'
#' @param state,timer,nodeid,count,n_nodes  As in [step_si()].
#' @param from_state Integer state code an agent must occupy to be eligible.
#' @param to_state   Integer (untimed) state code an agent moves to on expiry.
#' @return An integer vector of per-node transition counts (length `n_nodes`).
#' @export
step_timer_expire <- function(state, timer, nodeid, count, n_nodes, from_state, to_state) .Call(wrap__step_timer_expire, state, timer, nodeid, count, n_nodes, from_state, to_state)

#' Generic timed transition `from_state -> to_state` into a TIMED destination.
#'
#' Like [step_timer_expire()] but on expiry the agent's `timer` is reset to a fresh draw
#' from `duration` (the destination state's own clock — e.g. E→I sets the infectious
#' period, I→R sets a waning-immunity period). Returns per-node transition counts.
#'
#' @param state,timer,nodeid,count,n_nodes  As in [step_si()].
#' @param from_state Integer state code an agent must occupy to be eligible.
#' @param to_state   Integer state code an agent moves to on expiry.
#' @param duration   A Distribution for the destination state's timer.
#' @return An integer vector of per-node transition counts (length `n_nodes`).
#' @export
step_timer_expire_set <- function(state, timer, nodeid, count, n_nodes, from_state, to_state, duration) .Call(wrap__step_timer_expire_set, state, timer, nodeid, count, n_nodes, from_state, to_state, duration)

#' Apply constant-population SIR vital dynamics for one tick.
#'
#' `rate` is a per-node daily death-HAZARD-rate grid (a values map; the caller
#' converts a crude death rate of annual deaths per 1000 people to a daily rate,
#' e.g. `cdr / 1000 / 365`). For each of the first `count` agents, this converts the
#' node's rate to a probability `1 - exp(-rate)` (once per node, like transmission)
#' and, with that probability, "unalives" the agent and replaces it with a newborn:
#' the agent's `state` is reset to Susceptible and its `timer` to 0.
#'
#' The S/I/R node census is updated IN PLACE at column `tick + 1` (the working
#' column the caller has already carried forward): a death out of I decrements `I`
#' and increments `S`; a death out of R decrements `R` and increments `S`; a death
#' out of S nets to zero. Every event (from any compartment) is counted per node and
#' written to BOTH the `births` and `deaths` flow reports for `tick` (equal under
#' constant population). Agents are assumed to be in S, I, or R (it is the SIR
#' variant). Parallelized with private per-thread node buffers summed at the end.
#'
#' @param state   Per-agent `u8` state Column (mutated; deaths reset to Susceptible).
#' @param timer   Per-agent `u8` countdown Column (mutated; deaths reset to 0).
#' @param nodeid  Per-agent `u16` 0-based node-id Column.
#' @param count   Number of active agents to process.
#' @param rate    Per-node daily death-hazard-rate grid (`n_ticks x n_nodes`, from
#'   [values_map()]); column `tick` is read.
#' @param s_count,i_count,r_count  `n_ticks x n_nodes` i32 census Columns kept in
#'   sync (mutated at column `tick + 1`).
#' @param births,deaths  `(n_ticks-1) x n_nodes` i32 flow Columns; column `tick`
#'   receives the per-node event counts (equal; mutated).
#' @param tick    0-based tick index.
#' @return `NULL` (invisibly); the Columns are modified in place.
#' @export
constant_pop_vitals_sir <- function(state, timer, nodeid, count, rate, s_count, i_count, r_count, births, deaths, tick) .Call(wrap__constant_pop_vitals_sir, state, timer, nodeid, count, rate, s_count, i_count, r_count, births, deaths, tick)

#' Import new infectious cases from a schedule, activating reserved agent slots.
#'
#' For the given `tick`, scans the schedule (parallel `sched_tick` / `sched_node` /
#' `sched_count` vectors) and, for every entry whose `sched_tick == tick`, activates
#' `sched_count` new agents in node `sched_node`: each takes the next free slot after
#' the active `count`, is set Infectious with a `timer` drawn from `duration`, and
#' has its `nodeid` set. The new agents must fit in the reserved capacity (the
#' `state`/`timer`/`nodeid` Columns are allocated larger than the initial `count`).
#' Per-node import counts are added to the I census at column `tick + 1` and written
#' to the `importations` flow at column `tick`.
#'
#' Returns the new active agent count (the caller stores it back into `people$count`).
#' Sequential — it touches only the handful of imported slots, not all agents.
#'
#' @param state   Per-agent `u8` state Column (capacity-sized; imported slots set to I).
#' @param timer   Per-agent `u8` timer Column (imported slots set from `duration`).
#' @param nodeid  Per-agent `u16` node-id Column (imported slots set to their node).
#' @param count   Current active agent count (the first free slot).
#' @param i_count `n_ticks x n_nodes` i32 I census Column (mutated at `tick + 1`).
#' @param importations `(n_ticks-1) x n_nodes` i32 flow Column (set at `tick`).
#' @param sched_tick,sched_node,sched_count  Equal-length integer schedule vectors.
#' @param duration A Distribution for the imported cases' infectious timer.
#' @param tick    0-based tick index.
#' @return The new active agent count (`count` plus the number imported this tick).
#' @export
import_infections <- function(state, timer, nodeid, count, i_count, importations, sched_tick, sched_node, sched_count, duration, tick) .Call(wrap__import_infections, state, timer, nodeid, count, i_count, importations, sched_tick, sched_node, sched_count, duration, tick)

#' Build an [AliasedDistribution] from a vector of non-negative bin counts.
#'
#' The probability of drawing bin `i` (0-based) is `counts[i] / sum(counts)`. Counts
#' are rounded to whole numbers; they must be finite and non-negative and sum to a
#' positive total. A typical use is the per-age-bin population of a demographic
#' pyramid (e.g. males + females in each five-year band).
#'
#' @param counts A numeric vector of non-negative per-bin counts (length >= 1).
#' @return An `AliasedDistribution` object.
#' @examples
#' d <- aliased_distribution(c(10, 30, 60))   # bin 2 drawn ~60% of the time
#' table(d$sample_n(10000L))                  # 0-based bin indices
#' @export
aliased_distribution <- function(counts) .Call(wrap__aliased_distribution, counts)

#' Build a [KaplanMeierEstimator] from cumulative deaths by year.
#'
#' `cumulative_deaths[y]` is the number of a synthetic cohort dead by the end of year
#' `y`; it must be non-negative and monotonically non-decreasing. Values are rounded to
#' whole numbers. (A leading zero is prepended internally; do not include it yourself.)
#'
#' @param cumulative_deaths A non-decreasing numeric vector of cumulative deaths by
#'   year (length >= 1).
#' @return A `KaplanMeierEstimator` object.
#' @examples
#' # toy life table: 10 deaths/year for 80 years, then 100/year for 21 more
#' km <- kaplan_meier_estimator(cumsum(c(rep(10, 80), rep(100, 21))))
#' @export
kaplan_meier_estimator <- function(cumulative_deaths) .Call(wrap__kaplan_meier_estimator, cumulative_deaths)

#' Apply natural mortality for one tick, returning deaths per node by compartment.
#'
#' For each of the first `count` living agents (state != D) whose `dod` (an absolute
#' tick) is `<= tick`, sets the agent's `state` to D and tallies the death against the
#' compartment it occupied. Returns `list(m, s, e, i, r)` of per-node death counts; the
#' caller decrements those census compartments (and records the total deaths flow).
#'
#' @param state   Per-agent `u8` state Column (mutated; the deceased become D = 255).
#' @param dod     Per-agent `u32` date-of-death Column (an absolute tick index).
#' @param nodeid  Per-agent `u16` 0-based node-id Column.
#' @param count   Number of active agents to process.
#' @param n_nodes Number of nodes (the length of each returned vector).
#' @param tick    0-based tick index; agents with `dod <= tick` die.
#' @return `list(m, s, e, i, r)` of `integer[n_nodes]` death counts by source compartment.
#' @export
mortality <- function(state, dod, nodeid, count, n_nodes, tick) .Call(wrap__mortality, state, dod, nodeid, count, n_nodes, tick)

#' Apply crude-birth-rate births for one tick; newborns enter maternal immunity (M).
#'
#' For each of the first `count` living agents, draws a birth with per-node probability
#' `1 - exp(-birth_rate[node, tick])`. Each birth activates the next reserved slot as a
#' new agent: state M, `timer` from `maternal_duration`, `dob = tick`, and `dod = tick`
#' plus a Kaplan–Meier age at death (from `km`). Returns `list(count, born)`: the new
#' active count (store it back into `people$count`) and the per-node birth count (add it
#' to the `M` census and a birth report). Capped at the allocated capacity.
#'
#' @param state    Per-agent `u8` state Column (capacity-sized; newborn slots set to M).
#' @param timer    Per-agent `u16` timer Column (newborn slots set from `maternal_duration`).
#' @param nodeid   Per-agent `u16` node-id Column (newborn slots set to the parent's node).
#' @param dob      Per-agent `i32` date-of-birth Column (newborn slots set to `tick`).
#' @param dod      Per-agent `u32` date-of-death Column (newborn slots set via `km`).
#' @param count    Current active agent count (the first free slot).
#' @param n_nodes  Number of nodes (the length of the returned `born` vector).
#' @param birth_rate `n_ticks x n_nodes` f64 daily-birth-rate grid; column `tick` is read.
#' @param maternal_duration A Distribution for the newborns' maternal-immunity timer.
#' @param km       A KaplanMeierEstimator giving each newborn its age at death.
#' @param tick     0-based tick index.
#' @return `list(count = <new active count>, born = integer[n_nodes])`.
#' @export
births <- function(state, timer, nodeid, dob, dod, count, n_nodes, birth_rate, maternal_duration, km, tick) .Call(wrap__births, state, timer, nodeid, dob, dod, count, n_nodes, birth_rate, maternal_duration, km, tick)

#' A parameterized probability distribution that can be sampled repeatedly.
#'
#' Build one with a family constructor such as `dist_normal()` or `dist_constant()`,
#' then either sample it from Rust via `sample()` (Pattern B: the caller owns the
#' RNG and passes it in), or from R via `$sample_one()` / `$sample_n()`.
#'
#' Draws are always floating-point. Callers that need integer values (e.g. a
#' whole-tick state timer) are responsible for rounding or truncating as
#' appropriate — the simulation kernels round to the nearest tick.
#'
#' The handle is opaque to R — it is passed to simulation kernels (e.g.
#' `step_sir` or `transmission`) by reference, so the same object can be reused
#' every tick and shared across all worker threads.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `sample_one`}{
#'Draw a single sample using a thread-local RNG.
#'
#'Convenience for interactive use. Simulation kernels do not call this — they
#'use the internal sampler with an explicit, reusable RNG for performance.
#'
#' \subsection{return}{
#'A single numeric (double) draw from the distribution.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `sample_n`}{
#'Draw `n` samples using a thread-local RNG, returned as a numeric vector.
#'
#'Drawing a whole batch in one call avoids per-sample R↔Rust overhead, which
#'makes it practical to validate the sampler against large empirical samples
#'(e.g. one million draws) from R.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`n`}{Number of samples to draw; must be non-negative.}
#'}}
#' \subsection{return}{
#'A numeric (double) vector of length `n`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
Distribution <- new.env(parent = emptyenv())

Distribution$sample_one <- function() .Call(wrap__Distribution__sample_one, self)

Distribution$sample_n <- function(n) .Call(wrap__Distribution__sample_n, self, n)

#' @rdname Distribution
#' @usage NULL
#' @export
`$.Distribution` <- function (self, name) { func <- Distribution[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Distribution` <- `$.Distribution`

#' A Rust-owned, dtype-tagged property array (1-D scalar, or a 2-D vector report).
#'
#' Allocate one with [allocate_scalar()] (`nrows` elements, `ncols == 1`) or
#' [allocate_vector()] (`nrows`-per-slot × `ncols` slots, stored COLUMN-MAJOR so a
#' whole slot/time-slice is contiguous). The data is held in Rust and exposed to
#' R only as an opaque handle; use `$values()` to copy a snapshot back into an R
#' vector (or matrix, when `ncols > 1`) for inspection, `$fill()` / `$set()` to
#' write, and `$length()` / `$dtype()` to query. The simulation step kernels
#' operate on the buffer in place with no copies.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `length`}{
#'Number of elements in the array.
#' \subsection{return}{
#'An integer length.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `dtype`}{
#'The element data type as a string (e.g. `"u8"`, `"f32"`).
#' \subsection{return}{
#'A length-1 character vector.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `values`}{
#'Copy the array into an R vector for inspection (NOT a view — a snapshot).
#'
#'Integer-width types (i8, u8, i16, u16, i32) widen to R `integer`; `u32`,
#'`f32`, and `f64` widen to R `double` (since `u32` overflows R's signed
#'32-bit integer). This O(n) copy is the only place data leaves Rust.
#'
#'For a 2-D column (`n_slices > 1`, from [allocate_vector()]) the result carries
#'a `dim` attribute and reads back as an `n_slices × slice_len` R matrix (e.g.
#'`n_ticks × n_nodes`), so row `t` is tick `t`'s per-node vector; otherwise a
#'plain vector. The snapshot is transposed during the copy (our buffer is
#'slice-major, R matrices are column-major) — inexpensive, inspection-only.
#'
#' \subsection{return}{
#'A numeric vector (or matrix) — integer or double — of `length()` elements.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `fill`}{
#'Set every element to `value`, cast to the array's data type.
#'
#'For integer-typed arrays the value is truncated toward zero (e.g. `2.9`
#'becomes `2`); out-of-range values wrap per Rust's `as` cast.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`value`}{A single numeric value to broadcast across the array.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set`}{
#'Overwrite the array from an R numeric vector (integer or double).
#'
#'The input length must equal `length()`. Each element is cast to the array's
#'data type (integer-typed arrays truncate toward zero). Useful for setup —
#'e.g. writing per-agent node assignments or seeding initial states from R.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`values`}{A numeric vector of length `length()`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `col`}{
#'Read one column (`slot`) of a 2-D Column as an R vector snapshot.
#'
#'Returns the `slice_len` values in column `slot` (e.g. all nodes for one tick),
#'widened to R `integer`/`double` like [values()]. For a scalar column the only
#'valid `slot` is 0 (the whole vector).
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`slot`}{0-based column index, less than the number of columns.}
#'}}
#' \subsection{return}{
#'A numeric vector of length `slice_len`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set_col`}{
#'Write `values` into one column (`slot`) of a 2-D Column, in place.
#'
#'`values` must have length `slice_len`; each element is cast to the column's
#'data type. Lets the caller update a single column (e.g. one tick's per-node
#'slice — a derived population total) without rewriting the whole buffer.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`slot`}{  0-based column index, less than the number of columns.}
#'\item{`values`}{A numeric vector of length `slice_len`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `squash`}{
#'Compact the first `length(keep)` elements in place, keeping those flagged `TRUE`.
#'
#'Drops elements where `keep` is `FALSE`/`NA`, shifting the survivors to the front
#'(order preserved), and returns the number kept. Use it to reclaim the slots of
#'deceased agents: apply the SAME `keep` mask to every per-agent Column (so they stay
#'aligned) and set the active count to the returned value. The R [squash()] helper
#'does exactly this across a people environment. Only valid for a 1-D (scalar) Column.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`keep`}{A logical vector whose length is at most the column length (typically the active agent count).}
#'}}
#' \subsection{return}{
#'The number of kept elements (an integer); elements past it are left as-is.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
Column <- new.env(parent = emptyenv())

Column$length <- function() .Call(wrap__Column__length, self)

Column$dtype <- function() .Call(wrap__Column__dtype, self)

Column$values <- function() .Call(wrap__Column__values, self)

Column$fill <- function(value) .Call(wrap__Column__fill, self, value)

Column$set <- function(values) .Call(wrap__Column__set, self, values)

Column$col <- function(slot) .Call(wrap__Column__col, self, slot)

Column$set_col <- function(slot, values) .Call(wrap__Column__set_col, self, slot, values)

Column$squash <- function(keep) .Call(wrap__Column__squash, self, keep)

#' @rdname Column
#' @usage NULL
#' @export
`$.Column` <- function (self, name) { func <- Column[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Column` <- `$.Column`

#' A discrete distribution over bin indices `0..n`, sampled by the Vose alias method.
#'
#' Construct with [aliased_distribution()] from a vector of non-negative counts; the
#' probability of drawing bin `i` is `counts[i] / sum(counts)`. Draws are 0-based bin
#' indices. The handle is opaque to R.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `sample_one`}{
#'Draw a single bin index (0-based) using a thread-local RNG.
#'
#' \subsection{return}{
#'A single integer bin index in `0..n_bins()`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `sample_n`}{
#'Draw `n` bin indices (0-based), returned as an integer vector.
#'
#'The draws are split across CPU cores (each with its own thread-local RNG), so
#'generating a national-scale population in one call is cheap.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`n`}{Number of samples to draw; must be non-negative.}
#'}}
#' \subsection{return}{
#'An integer vector of length `n` of bin indices in `0..n_bins()`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `n_bins`}{
#'The number of bins.
#' \subsection{return}{
#'An integer.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `total`}{
#'The total weight (sum of the original counts).
#' \subsection{return}{
#'A numeric scalar (the sum may exceed R's integer range).
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `alias`}{
#'The alias table (0-based partner bin per bin, or -1 for none). For inspection.
#' \subsection{return}{
#'An integer vector of length `n_bins()`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `probs`}{
#'The per-bin own-mass thresholds (out of `total()`). For inspection.
#' \subsection{return}{
#'A numeric vector of length `n_bins()`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
AliasedDistribution <- new.env(parent = emptyenv())

AliasedDistribution$sample_one <- function() .Call(wrap__AliasedDistribution__sample_one, self)

AliasedDistribution$sample_n <- function(n) .Call(wrap__AliasedDistribution__sample_n, self, n)

AliasedDistribution$n_bins <- function() .Call(wrap__AliasedDistribution__n_bins, self)

AliasedDistribution$total <- function() .Call(wrap__AliasedDistribution__total, self)

AliasedDistribution$alias <- function() .Call(wrap__AliasedDistribution__alias, self)

AliasedDistribution$probs <- function() .Call(wrap__AliasedDistribution__probs, self)

#' @rdname AliasedDistribution
#' @usage NULL
#' @export
`$.AliasedDistribution` <- function (self, name) { func <- AliasedDistribution[[name]]; environment(func) <- environment(); func }

#' @export
`[[.AliasedDistribution` <- `$.AliasedDistribution`

#' A Kaplan–Meier sampler over a cumulative-deaths-by-year life table.
#'
#' Construct with [kaplan_meier_estimator()] from a non-decreasing vector of
#' cumulative deaths by year. The handle is opaque to R.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `predict_year_of_death`}{
#'Predict a year of death for each individual given their current age in years.
#'
#'For each age, samples a year of death `>= age` and `<= max_year`, conditioned on
#'survival to that age (Kaplan–Meier). Ages must be in `0..=max_year`.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`ages_years`}{Integer vector of current ages in whole years.}
#'\item{`max_year`}{  Maximum year of death to consider; pass a negative value (e.g. `-1L`) to use the last year in the life table.}
#'}}
#' \subsection{return}{
#'An integer vector of predicted years of death (same length as input).
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `predict_age_at_death`}{
#'Predict an age at death (in DAYS) for each individual given their age in days.
#'
#'Samples the year of death as in [predict_year_of_death()], then a day within
#'that year: a uniform day of a later year, or — if death falls in the individual's
#'current year — a uniform day at or after their current day-of-year (so the
#'predicted age at death is never earlier than the current age). Ages in days must
#'be `< (max_year + 1) * 365`.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`ages_days`}{Integer vector of current ages in whole days.}
#'\item{`max_year`}{ Maximum year of death to consider; pass a negative value (e.g. `-1L`) to use the last year in the life table.}
#'}}
#' \subsection{return}{
#'An integer vector of predicted ages at death in days (same length).
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `cumulative_deaths`}{
#'The cumulative-deaths-by-year table (without the internal leading zero).
#' \subsection{return}{
#'A numeric vector of length equal to the number of years.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#' @examples
#'## ---- Method `predict_year_of_death` ---- ##
#'km <- kaplan_meier_estimator(cumsum(c(rep(10, 80), rep(100, 21))))
#'km$predict_year_of_death(c(40L, 50L, 60L), -1L)
#'
#'## ---- Method `predict_age_at_death` ---- ##
#'km <- kaplan_meier_estimator(cumsum(c(rep(10, 80), rep(100, 21))))
#'km$predict_age_at_death(c(40L, 50L, 60L) * 365L, -1L)
#'
#'
KaplanMeierEstimator <- new.env(parent = emptyenv())

KaplanMeierEstimator$predict_year_of_death <- function(ages_years, max_year) .Call(wrap__KaplanMeierEstimator__predict_year_of_death, self, ages_years, max_year)

KaplanMeierEstimator$predict_age_at_death <- function(ages_days, max_year) .Call(wrap__KaplanMeierEstimator__predict_age_at_death, self, ages_days, max_year)

KaplanMeierEstimator$cumulative_deaths <- function() .Call(wrap__KaplanMeierEstimator__cumulative_deaths, self)

#' @rdname KaplanMeierEstimator
#' @usage NULL
#' @export
`$.KaplanMeierEstimator` <- function (self, name) { func <- KaplanMeierEstimator[[name]]; environment(func) <- environment(); func }

#' @export
`[[.KaplanMeierEstimator` <- `$.KaplanMeierEstimator`

# nolint end
