# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib razer, .registration = TRUE
NULL

#' Named integer vector of epidemic compartment state codes.
#'
#' Returns `c(S=0L, E=1L, I=2L, R=3L, D=-1L)`. Use these constants to set
#' and test the `state` property on a people frame.
#'
#' @return Named integer vector with elements S, E, I, R, D.
#' @export
laser_states <- function() .Call(wrap__laser_states)

#' Stochastic S→I transmission step (SI / SIR kernel).
#'
#' **Parallelism:** the active agent array is split into fixed chunks — one per
#' Rayon worker thread — matching the `prange` pattern. The aggregation phase
#' uses a thread-local fold then reduces by element-wise summation. The FOI
#' phase runs each chunk independently; RNG is thread-local (`rand::thread_rng()`).
#'
#' All operations are performed in-place on the backing arrays; no copies are made.
#'
#' Node-level I counts are computed from current agent states and written to
#' `nodes$I` (overwriting the previous value).
#'
#' **Spatial coupling.** `network` is an `n_nodes × n_nodes` matrix whose
#' `[i, j]` entry is the fraction of node *i*'s force of infection exported to
#' node *j*. The per-node force is redistributed before agents are infected:
#' `lambda[k] = r[k]·(1 - rowSums(W)[k]) + (t(W) %*% r)[k]` with local rate
#' `r[k] = beta · I[k] / N[k]`. Total force is conserved (off-diagonal row sums
#' should be in `[0, 1]`). Use an **all-zero matrix** for independent nodes (no
#' spatial mixing), which leaves `lambda[k] = r[k]`.
#'
#' **Required people properties:** `state` (integer), `node` (integer, 0-based),
#' `timer` (integer).
#' **Required nodes properties:** `N` (integer, total population per node),
#' `I` (integer, will be overwritten).
#'
#' @param people       LaserFrame of agents.
#' @param nodes        LaserFrame of patches/nodes.
#' @param beta         Transmission rate (force of infection per infectious contact per tick).
#' @param inf_dist     A `Distribution` (e.g. `dist_constant()` or `dist_normal()`) giving the
#'   infectious period in ticks; sampled per newly infected agent and written to
#'   `timer` on S→I (rounded to whole ticks, clamped to a minimum of 1).
#' @param network      An `n_nodes × n_nodes` numeric matrix whose `[i, j]` entry
#'   is the fraction of node `i`'s force of infection exported to node `j` (see
#'   Spatial coupling above). Use an all-zero matrix for independent nodes.
#' @export
step_transmission_si <- function(people, nodes, beta, inf_dist, network) .Call(wrap__step_transmission_si, people, nodes, beta, inf_dist, network)

#' Stochastic S→E exposure step (SEIR kernel).
#'
#' Same FOI computation and parallelism as `step_transmission_si`, but newly
#' exposed agents move to state E and `timer` is set to a draw from `exp_dist`
#' (incubation period). Pair with `step_exposed_ei` to complete E→I.
#'
#' Spatial coupling via `network` works exactly as in [step_transmission_si()]:
#' an `n_nodes × n_nodes` matrix redistributes the per-node force of infection
#' before agents are exposed. Use an all-zero matrix for independent nodes.
#'
#' **Required people properties:** `state`, `node`, `timer` (all integer).
#' **Required nodes properties:** `N`, `I` (integer; `I` is overwritten).
#'
#' @param people        LaserFrame of agents.
#' @param nodes         LaserFrame of patches/nodes.
#' @param beta          Transmission rate.
#' @param exp_dist      A `Distribution` (e.g. `dist_constant()` or `dist_normal()`) giving the
#'   incubation period in ticks; sampled per newly exposed agent and written to
#'   `timer` on S→E (rounded to whole ticks, clamped to a minimum of 1).
#' @param network       An `n_nodes × n_nodes` numeric matrix of exported
#'   force-of-infection fractions (see [step_transmission_si()]); all-zero for
#'   independent nodes.
#' @export
step_transmission_se <- function(people, nodes, beta, exp_dist, network) .Call(wrap__step_transmission_se, people, nodes, beta, exp_dist, network)

#' Generalized timer-expiry transition into an *absorbing* (untimed) state.
#'
#' For each agent currently in `from_state`, decrements `timer` by 1; when the
#' timer reaches 0 the agent moves to `to_state` and its timer is left at 0. The
#' destination carries no duration of its own — this is the "transition to an
#' absorbing state" generalization (laser-generic's `nb_timer_update`), e.g.
#' I→S in SIS, I→R in SIR, or R→S waning.
#'
#' This is the engine behind [step_infectious_is()] (I→S) and
#' [step_recovered_rs()] (R→S):
#' `step_timer_expire(people, laser_states()[["I"]], laser_states()[["S"]])`
#' is exactly `step_infectious_is(people)`.
#'
#' **Required people properties:** `state`, `timer` (both integer).
#'
#' @param people     LaserFrame of agents.
#' @param from_state Integer state code an agent must currently occupy to be eligible.
#' @param to_state   Integer state code an agent moves to when its timer expires.
#' @export
step_timer_expire <- function(people, from_state, to_state) .Call(wrap__step_timer_expire, people, from_state, to_state)

#' Generalized timer-expiry transition into a state that has *its own* duration.
#'
#' For each agent currently in `from_state`, decrements `timer` by 1; when the
#' timer reaches 0 the agent moves to `to_state` and `timer` is reset to a fresh
#' per-agent draw from `duration_dist` (rounded to whole ticks, clamped to a
#' minimum of 1). This is the "transition to a state with its own duration timer"
#' generalization (laser-generic's `nb_timer_update_timer_set`), e.g. E→I in
#' SEIR or I→R with waning in SEIRS.
#'
#' This is the engine behind [step_exposed_ei()] (E→I) and
#' [step_infectious_ir()] (I→R):
#' `step_timer_expire_set(people, laser_states()[["E"]], laser_states()[["I"]], inf_dist)`
#' is exactly `step_exposed_ei(people, inf_dist)`.
#'
#' **RNG:** thread-local (Pattern B) — each Rayon worker draws from its own
#' `thread_rng`; the single `duration_dist` handle is shared across threads by
#' reference.
#'
#' **Required people properties:** `state`, `timer` (both integer).
#'
#' @param people        LaserFrame of agents.
#' @param from_state    Integer state code an agent must currently occupy to be eligible.
#' @param to_state      Integer state code an agent moves to when its timer expires.
#' @param duration_dist A `Distribution` (e.g. `dist_constant()` or `dist_normal()`)
#'   giving the destination state's duration in ticks; sampled per transitioning
#'   agent and written to `timer`.
#' @export
step_timer_expire_set <- function(people, from_state, to_state, duration_dist) .Call(wrap__step_timer_expire_set, people, from_state, to_state, duration_dist)

#' Timer-based E→I transition (SEIR kernel).
#'
#' For each exposed agent, decrements `timer` by 1. When `timer` reaches 0 the
#' agent transitions to state I and `timer` is set to a fresh draw from
#' `inf_dist`, the infectious-period distribution. Pass `dist_constant(d)` for a
#' fixed period of `d` ticks, or e.g. `dist_normal(mean, variance)` for a stochastic
#' per-agent period. Draws are rounded to the nearest tick and clamped to a
#' minimum of 1.
#'
#' A fixed-state shorthand for
#' [step_timer_expire_set()]`(people, E, I, inf_dist)`.
#'
#' **RNG:** thread-local — each Rayon worker draws from its own `thread_rng`
#' (Pattern B: the kernel owns the RNG and passes it into the sampler). The
#' single `inf_dist` handle is shared across threads by reference.
#'
#' @param people    LaserFrame of agents.
#' @param inf_dist  A `Distribution` (e.g. from `dist_constant()` or `dist_normal()`)
#'   giving the infectious period in ticks; sampled and written to `timer` on E→I.
#' @export
step_exposed_ei <- function(people, inf_dist) .Call(wrap__step_exposed_ei, people, inf_dist)

#' Timer-based I→R transition (SIR / SEIR / SEIRS kernel).
#'
#' For each infectious agent, decrements `timer` by 1. When `timer` reaches 0
#' the agent transitions to state R and `timer` is set to a draw from `imm_dist`,
#' the immunity (waning) period.
#'
#' A fixed-state shorthand for
#' [step_timer_expire_set()]`(people, I, R, imm_dist)`.
#'
#' For SEIRS, pass the desired immunity distribution so that `step_recovered_rs`
#' counts down R→S from a fresh per-agent draw. For SIR and SEIR (no waning,
#' `step_recovered_rs` never called) the R timer is never read, so any
#' distribution works — `dist_constant(0)` is the conventional "don't care".
#'
#' **RNG:** thread-local — each Rayon worker draws from its own `thread_rng`
#' (Pattern B). The single `imm_dist` handle is shared across threads by reference.
#'
#' @param people    LaserFrame of agents.
#' @param imm_dist  A `Distribution` (e.g. `dist_constant()` or `dist_normal()`) giving the
#'   immunity period in ticks; sampled and written to `timer` on I→R (rounded to
#'   whole ticks, clamped to a minimum of 1). Use `dist_constant(0)` for SIR / SEIR.
#' @export
step_infectious_ir <- function(people, imm_dist) .Call(wrap__step_infectious_ir, people, imm_dist)

#' Timer-based I→S transition for SIS models (no immunity).
#'
#' For each infectious agent, decrements `timer` by 1. When `timer` reaches 0
#' the agent transitions directly back to state S.
#'
#' A fixed-state shorthand for [step_timer_expire()]`(people, I, S)`.
#'
#' @param people LaserFrame of agents.
#' @export
step_infectious_is <- function(people) .Call(wrap__step_infectious_is, people)

#' Timer-based R→S transition for waning-immunity models.
#'
#' For each recovered agent, decrements `timer` by 1. When `timer` reaches 0
#' the agent becomes susceptible again (state S).
#'
#' A fixed-state shorthand for [step_timer_expire()]`(people, R, S)`.
#'
#' @param people LaserFrame of agents.
#' @export
step_recovered_rs <- function(people) .Call(wrap__step_recovered_rs, people)

#' Stochastic mortality step using a crude death rate.
#'
#' For each living (non-D) agent, draws Bernoulli(`cdr`) for death.
#' Agents that die have their state set to D (-1) and `timer` set to 0.
#' Dead agents remain in the frame — call `$squash(people$state >= 0L)`
#' periodically to compact.
#'
#' Each agent's draw is independent; Rayon assigns a fixed slice to each worker
#' thread. RNG is thread-local (no locking).
#'
#' @param people LaserFrame of agents.
#' @param cdr    Crude death rate per agent per tick (probability in \[0, 1\]).
#' @export
step_mortality_cdr <- function(people, cdr) .Call(wrap__step_mortality_cdr, people, cdr)

#' Stochastic birth step using a crude birth rate.
#'
#' **Parallelism:** the Bernoulli draw (does this agent give birth?) is
#' parallelised across all active agents. The subsequent bookkeeping —
#' incrementing `count` and writing new-agent properties — is serial because
#' it modifies the frame's active count.
#'
#' For each active (non-D) agent, draws Bernoulli(`cbr`) for a birth event.
#' Each birth creates one new agent that inherits the parent's `node` and
#' starts in state S with `timer = 0`. Other scalar properties of new agents
#' take the default value set at `add_scalar_property` time.
#'
#' Excess births beyond `capacity - count` are silently dropped.
#'
#' **Required people properties:** `state`, `node`, `timer` (all integer).
#'
#' @param people LaserFrame of agents.
#' @param cbr    Crude birth rate per agent per tick (probability in \[0, 1\]).
#' @export
step_births_cbr <- function(people, cbr) .Call(wrap__step_births_cbr, people, cbr)

#' Create a normal (Gaussian) distribution.
#'
#' The second argument is the **variance** (σ²), not the standard deviation, to
#' match the way variance is usually quoted in statistical models. The standard
#' deviation passed to the underlying sampler is `sqrt(variance)`.
#'
#' @param mean      Mean (μ) of the distribution.
#' @param variance  Variance (σ²); must be non-negative.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_normal(7, 4)   # mean 7, variance 4 (sd 2)
#' d$sample_one()
#' @export
dist_normal <- function(mean, variance) .Call(wrap__dist_normal, mean, variance)

#' Create a degenerate (constant) distribution that always returns `value`.
#'
#' Use this as a fixed-duration drop-in wherever a `Distribution` is required —
#' e.g. a deterministic infectious period of exactly `value` ticks.
#'
#' @param value The constant value returned by every draw.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_constant(10)   # always 10
#' d$sample_one()
#' @export
dist_constant <- function(value) .Call(wrap__dist_constant, value)

#' Create a continuous uniform distribution on the half-open interval [low, high).
#'
#' Every value in `[low, high)` is equally likely. The mean is `(low + high) / 2`.
#'
#' @param low   Inclusive lower bound.
#' @param high  Exclusive upper bound; must be strictly greater than `low`.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_uniform(3, 8)   # values in [3, 8), mean 5.5
#' d$sample_one()
#' @export
dist_uniform <- function(low, high) .Call(wrap__dist_uniform, low, high)

#' Create a gamma distribution parameterized by shape and scale.
#'
#' Uses the shape–scale (k, θ) parameterization: the mean is `shape * scale` and
#' the variance is `shape * scale^2`. Draws are strictly positive, which makes the
#' gamma a natural choice for right-skewed, always-positive durations.
#'
#' @param shape  Shape parameter k; must be finite and positive.
#' @param scale  Scale parameter θ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_gamma(2, 3)   # mean 6, variance 18
#' d$sample_one()
#' @export
dist_gamma <- function(shape, scale) .Call(wrap__dist_gamma, shape, scale)

#' Create a Poisson distribution with rate (mean) `lambda`.
#'
#' Draws are non-negative integer counts (returned as doubles) with mean and
#' variance both equal to `lambda`. Useful for count-valued durations.
#'
#' @param lambda  Rate / mean λ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_poisson(5)   # mean 5, integer-valued draws
#' d$sample_one()
#' @export
dist_poisson <- function(lambda) .Call(wrap__dist_poisson, lambda)

#' Create a beta distribution on the open interval (0, 1).
#'
#' Parameterized by the two positive shape parameters α and β. The mean is
#' `alpha / (alpha + beta)`.
#'
#' @param alpha  First shape parameter (α); must be finite and positive.
#' @param beta   Second shape parameter (β); must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_beta(2, 5)   # mean 2/7 ≈ 0.286, support (0, 1)
#' d$sample_one()
#' @export
dist_beta <- function(alpha, beta) .Call(wrap__dist_beta, alpha, beta)

#' Create an exponential distribution with rate `rate`.
#'
#' Draws are strictly positive with mean `1 / rate` and variance `1 / rate^2`.
#'
#' @param rate  Rate parameter λ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_exp(0.5)   # mean 2
#' d$sample_one()
#' @export
dist_exp <- function(rate) .Call(wrap__dist_exp, rate)

#' Create a logistic distribution with the given location and scale.
#'
#' Symmetric about `location` (its mean and median); the variance is
#' `scale^2 * pi^2 / 3`.
#'
#' @param location  Location parameter μ (the mean); must be finite.
#' @param scale     Scale parameter s; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_logistic(4, 2)   # mean 4
#' d$sample_one()
#' @export
dist_logistic <- function(location, scale) .Call(wrap__dist_logistic, location, scale)

#' Create a log-normal distribution.
#'
#' A variable whose natural logarithm is `Normal(meanlog, sdlog)`. Draws are
#' strictly positive. The median is `exp(meanlog)` and the mean is
#' `exp(meanlog + sdlog^2 / 2)`. `meanlog` and `sdlog` are the log-space
#' parameters, matching R's `qlnorm(p, meanlog, sdlog)`.
#'
#' @param meanlog  Mean of the underlying normal (in log space); must be finite.
#' @param sdlog    Standard deviation of the underlying normal; must be finite
#'   and non-negative.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_lognormal(0, 0.5)   # median 1
#' d$sample_one()
#' @export
dist_lognormal <- function(meanlog, sdlog) .Call(wrap__dist_lognormal, meanlog, sdlog)

#' Great-circle distance matrix between geographic points.
#'
#' Ports laser-core's `distance` (all-pairs case): given the latitudes and
#' longitudes of `N` points in decimal degrees, returns the symmetric `N × N`
#' matrix whose `[i, j]` entry is the haversine great-circle distance, in
#' **kilometres**, between point `i` and point `j`. The diagonal is zero.
#'
#' The haversine formula (see <https://en.wikipedia.org/wiki/Haversine_formula>)
#' is evaluated with a mean Earth radius of 6371 km, matching laser-core.
#'
#' @param latitude  Numeric vector of latitudes in decimal degrees, in `[-90, 90]`.
#' @param longitude Numeric vector of longitudes in decimal degrees, in `[-180, 180]`.
#'   Must be the same length as `latitude`.
#' @return An `N × N` numeric matrix of pairwise distances in kilometres
#'   (symmetric, zero diagonal), where `N` is the number of points.
#' @examples
#' # London and Paris, ~344 km apart:
#' d <- distances(c(51.5074, 48.8566), c(-0.1278, 2.3522))
#' d[1, 2]
#' @export
distances <- function(latitude, longitude) .Call(wrap__distances, latitude, longitude)

#' Gravity migration-network model.
#'
#' `network[i, j] = k * pops[i]^a * pops[j]^b / distance[i, j]^c`, with a zero
#' diagonal (no self-migration). Port of laser-core's `gravity`.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix (e.g. from
#'   [distances()]).
#' @param k Scaling constant for the overall flow magnitude (non-negative).
#' @param a Exponent on the origin population.
#' @param b Exponent on the destination population.
#' @param c Exponent on the distance (larger `c` = stronger distance decay).
#' @return An `N × N` numeric matrix; `[i, j]` is the migration weight from node
#'   i to node j.
#' @export
gravity <- function(pops, distances, k, a, b, c) .Call(wrap__gravity, pops, distances, k, a, b, c)

#' Radiation migration-network model (Simini et al., Nature 2012).
#'
#' For each source `i`, destinations are ranked by distance and the weight to
#' destination `j` is
#' `k * p_i * p_j / (p_i + s) / (p_i + p_j + s)`, where `s` is the total
#' population of all nodes as close or closer to `i` than `j` (excluding the home
#' population `p_i` when `include_home = FALSE`). Port of laser-core's
#' `radiation`. The diagonal is 0.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix.
#' @param k Scaling constant for the flow magnitude (non-negative).
#' @param include_home Logical; whether the home (source) population is included
#'   in the "as close or closer" cumulative sum.
#' @return An `N × N` numeric migration-weight matrix (generally not symmetric).
#' @export
radiation <- function(pops, distances, k, include_home) .Call(wrap__radiation, pops, distances, k, include_home)

#' Competing-destinations migration model (Fotheringham, 1984).
#'
#' Starts from the [gravity()] weights and multiplies each `[i, j]` by an
#' accessibility term `(Σ_k p_k^b / d_jk^c)^delta`, summed over competing
#' destinations `k ∉ {i, j}`. Port of laser-core's `competing_destinations`. The
#' diagonal is 0.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix.
#' @param k Scaling constant for the flow magnitude (non-negative).
#' @param a Exponent on the origin population (gravity term).
#' @param b Exponent on the destination population (gravity and competition terms).
#' @param c Exponent on distance (gravity and competition terms).
#' @param delta Exponent on the competing-destinations accessibility term.
#' @return An `N × N` numeric migration-weight matrix (generally not symmetric).
#' @export
competing_destinations <- function(pops, distances, k, a, b, c, delta) .Call(wrap__competing_destinations, pops, distances, k, a, b, c, delta)

#' Stouffer's intervening-opportunities migration model (Stouffer, 1940).
#'
#' For each source `i` and destination `j`,
#' `network[i, j] = k * p_i^a * (p_j / s)^b`, where `s` is the cumulative
#' population as close or closer to `i` than `j` (excluding the home population
#' when `include_home = FALSE`); the nearest node (the source) gets weight 0.
#' Port of laser-core's `stouffer`. The diagonal is 0.
#'
#' @param pops      Numeric vector of node populations (length N, non-negative).
#' @param distances Symmetric `N × N` numeric distance matrix.
#' @param k Scaling constant for the flow magnitude (non-negative).
#' @param a Exponent on the origin population.
#' @param b Exponent on the destination/cumulative-population ratio.
#' @param include_home Logical; whether the home population is included in the
#'   cumulative sum.
#' @return An `N × N` numeric migration-weight matrix (generally not symmetric).
#' @export
stouffer <- function(pops, distances, k, a, b, include_home) .Call(wrap__stouffer, pops, distances, k, a, b, include_home)

#' Cap each row sum of a network matrix at `max_rowsum`.
#'
#' Rows whose total exceeds `max_rowsum` are scaled down proportionally so they
#' sum to exactly `max_rowsum`; smaller rows are left unchanged. Port of
#' laser-core's `row_normalizer`. Useful to bound the fraction of a node's force
#' of infection that is exported before passing the matrix as the transmission
#' `network`.
#'
#' @param network    A square non-negative numeric matrix.
#' @param max_rowsum Maximum allowed row sum, in `[0, 1]`.
#' @return The row-capped matrix, same shape as `network`.
#' @export
row_normalizer <- function(network, max_rowsum) .Call(wrap__row_normalizer, network, max_rowsum)

#' Allocate a fresh, zero-filled property array of a given type and length.
#'
#' Returns an opaque [Column] handle backed by a Rust-owned buffer. Choose the
#' narrowest type that fits the data to minimize memory (e.g. `"u8"` for a small
#' set of disease-state codes).
#'
#' @param dtype Element type, one of `"i8"`, `"u8"`, `"i16"`, `"u16"`, `"i32"`,
#'   `"u32"`, `"f32"`, `"f64"` (aliases: `"int8"`, `"uint8"`/`"raw"`, …,
#'   `"integer"` = i32, `"double"`/`"real"` = f64, `"single"` = f32).
#' @param count Array length (number of elements); a non-negative integer.
#' @return A [Column] object whose elements are all zero.
#' @examples
#' state <- allocate_scalar("u8", 5L)
#' state$dtype()    # "u8"
#' state$length()   # 5
#' state$values()   # 0 0 0 0 0
#' @export
allocate_scalar <- function(dtype, count) .Call(wrap__allocate_scalar, dtype, count)

#' Allocate a fresh, zero-filled 2-D property array (a per-slot report buffer).
#'
#' Returns an opaque [Column] of `n_slices * slice_len` elements laid out
#' SLICE-MAJOR (row-major): `n_slices` slices, each a contiguous run of `slice_len`
#' elements. Slice `s` is the block `s*slice_len .. (s+1)*slice_len`, so indexing
#' the FIRST dimension yields a contiguous array. The conventional use is a
#' time-series report with the **first dimension time and the second node** —
#' `allocate_vector(dtype, n_ticks, n_nodes)` — so each tick's per-node values are
#' contiguous (cache-friendly for the step kernels that fill one tick at a time).
#' `$values()` reads it back as an `n_slices × slice_len` (e.g. `n_ticks × n_nodes`)
#' R matrix, so row `t` is tick `t`'s vector.
#'
#' @param dtype     Element type (see [allocate_scalar()] for the accepted names).
#' @param n_slices  Number of slices — the first/outer dimension (e.g. the tick
#'   count). A non-negative integer.
#' @param slice_len Contiguous length of each slice — the inner dimension (e.g. the
#'   node count). A non-negative integer.
#' @return A [Column] of shape `n_slices × slice_len`, all elements zero.
#' @examples
#' recoveries <- allocate_vector("u32", 4L, 3L)   # 4 ticks x 3 nodes
#' dim(recoveries$values())                        # 4 3
#' @export
allocate_vector <- function(dtype, n_slices, slice_len) .Call(wrap__allocate_vector, dtype, n_slices, slice_len)

#' Carry a per-node counter forward one tick: copy column `tick` onto `tick + 1`.
#'
#' For a 2-D report [Column] (e.g. `n_ticks+1 × n_nodes`), copies the contiguous
#' slice for `tick` onto the slice for `tick + 1`. This seeds the next tick with the
#' current counts so a dynamics kernel can then update it in place — keeping the
#' census invariant `count[t+1] = count[t] ± delta`. Call it once per state that
#' must persist across ticks (e.g. S, I, R for an SIR model; add E for SEIR, or a
#' user-defined "V" vaccinated count). Works for any element type.
#'
#' @param counter A 2-D Column to carry forward.
#' @param tick    0-based source tick; column `tick` is copied onto column `tick+1`.
#' @return `NULL` (invisibly); `counter` is modified in place.
#' @examples
#' counts <- allocate_vector("i32", 3L, 2L)   # 3 ticks x 2 nodes
#' counts$set(c(5L, 7L, 0L, 0L, 0L, 0L))      # tick 0 = (5, 7)
#' carry_forward(counts, 0L)
#' counts$values()[2L, ]                       # 5 7  (carried to tick 1)
#' @export
carry_forward <- function(counter, tick) .Call(wrap__carry_forward, counter, tick)

#' Count occurrences of each value, NumPy `bincount`-style, into a buffer.
#'
#' For each bin `b` in `0..nbins`, computes how many elements of `values` equal
#' `b` and writes that into `counts[b]`. `values` must be an integer-typed
#' [Column] whose elements lie in `0..nbins` (they are used as bin indices);
#' `counts` is a numeric [Column] and the result is written into **slice `slot`**
#' of it — the `nbins` entries `slot*slice_len .. slot*slice_len + nbins` —
#' overwriting them while leaving the rest of the slice (and other slices)
#' untouched. For a scalar `counts` (shape `(1, n)`) the only slice is `slot = 0`,
#' the whole vector; for a 2-D report (e.g. `(n_ticks, n_nodes)`) `slot` selects a
#' tick's row. The work is parallelized with private per-thread histograms, so
#' there are no write collisions.
#'
#' @param values An integer-typed `Column` of bin indices (`i8`..`u32`).
#' @param nbins  Number of bins; a non-negative integer `<= counts`'s slice length.
#' @param counts A numeric `Column` that receives the counts (modified in place).
#' @param slot   Which slice of `counts` to write; a non-negative integer
#'   `< counts`'s slice count. Defaults to `0` (the whole vector for a scalar
#'   `counts`, or the first tick of a report). `@param` is optional.
#' @return `NULL` (invisibly); the result is written into `counts`.
#' @examples
#' values <- allocate_scalar("u16", 6L)
#' values$set(c(0, 1, 1, 2, 2, 2))
#' counts <- allocate_scalar("i32", 3L)
#' bincount(values, 3L, counts)
#' counts$values()   # 1 2 3
#' @noRd
bincount_impl <- function(values, nbins, counts, slot) .Call(wrap__bincount_impl, values, nbins, counts, slot)

#' Weighted bincount: sum each element's weight into its bin (NumPy
#' `bincount(values, weights=...)`).
#'
#' For each bin `b` in `0..nbins`, computes `sum of weights[i] over all i with
#' values[i] == b` and writes it into **slice `slot`** of `counts` (the entries
#' `slot*slice_len .. slot*slice_len + nbins`), overwriting them. `values` must be
#' an integer-typed [Column] of bin indices in `0..nbins`; `weights` is any numeric
#' [Column] (signed, unsigned, or floating point) the SAME length as `values`;
#' `counts` is a numeric [Column] whose slice length is `>= nbins`. For a scalar
#' `counts` the only slice is `slot = 0` (the whole vector); for a 2-D report
#' `slot` selects a tick's row. Parallelized with private per-thread accumulators,
#' so there are no write collisions.
#'
#' @param values  An integer-typed `Column` of bin indices (`i8`..`u32`).
#' @param weights A numeric `Column` (any type), the same length as `values`.
#' @param nbins   Number of bins; a non-negative integer `<= counts`'s slice length.
#' @param counts  A numeric `Column` that receives the sums (modified in place).
#' @param slot    Which slice of `counts` to write; a non-negative integer
#'   `< counts`'s slice count. Defaults to `0`.
#' @return `NULL` (invisibly); the result is written into `counts`.
#' @examples
#' values  <- allocate_scalar("u16", 5L); values$set(c(0, 0, 1, 2, 2))
#' weights <- allocate_scalar("f64", 5L); weights$set(c(1.5, 2.5, 4, 1, 3))
#' counts  <- allocate_scalar("f64", 3L)
#' bincountw(values, weights, 3L, counts)
#' counts$values()   # 4 4 4
#' @noRd
bincountw_impl <- function(values, weights, nbins, counts, slot) .Call(wrap__bincountw_impl, values, weights, nbins, counts, slot)

#' One SIR recovery step for tick `tick`: recover expired infectious agents.
#'
#' For each of the first `count` agents whose `state` is infectious (`I`),
#' decrements its `u8` `timer`; when the timer reaches zero the agent becomes
#' recovered (`R`). The number of recoveries per node is counted in parallel
#' (private per-thread node buffers, summed at the end) and applied as a delta to
#' column `tick + 1` of the census: `I` down, `R` up; the per-node recovery count is
#' also recorded in column `tick` of the `recoveries` flow report.
#'
#' The census is updated IN PLACE at column `tick + 1`, which the caller must have
#' already seeded by calling [carry_forward()] on each census counter for this tick
#' (S, I, R) — `sir_step` itself no longer carries the census forward.
#'
#' `i_count` / `r_count` are `n_ticks+1 × n_nodes` i32 census Columns; `recoveries`
#' is an `n_ticks × n_nodes` i32 flow Column.
#'
#' @param state      Per-agent `u8` state Column (mutated).
#' @param timer      Per-agent `u8` countdown Column (mutated).
#' @param nodeid     Per-agent `u16` 0-based node-id Column.
#' @param count      Number of active agents to process.
#' @param i_count,r_count  `n_ticks+1 × n_nodes` i32 census Columns (mutated at `tick+1`).
#' @param recoveries `n_ticks × n_nodes` i32 flow Column (mutated at `tick`).
#' @param tick       0-based tick index; the recovery delta is applied to column `tick+1`.
#' @return `NULL` (invisibly); the Columns are modified in place.
#' @export
sir_step <- function(state, timer, nodeid, count, i_count, r_count, recoveries, tick) .Call(wrap__sir_step, state, timer, nodeid, count, i_count, r_count, recoveries, tick)

#' Compute the per-node force of infection (FOI) for one tick.
#'
#' Computes the frequency-dependent, network-redistributed FOI **rate** into column
#' `tick` of `foi`. The local rate per node is
#' `r[k] = beta[k] * seasonality[k] * infected[k] / population[k]`, redistributed as
#' `foi[k] = r[k] * (1 - sum_j W[k, j]) + sum_i r[i] * W[i, k]`. `transmission()`
#' turns this rate into a per-tick probability `1 - exp(-foi)`. Call it after
#' `sir_step` and just before `transmission`.
#'
#' Index conventions: `infected` and `population` are census buffers read at the
#' POST-RECOVERY working column `tick + 1` (so agents recovering this tick are
#' excluded, and the denominator is the current population — which may change once
#' vital dynamics are added). `beta` and `seasonality` are exogenous modifier grids
#' read at the interval column `tick`. The result is written to `foi[tick]`.
#'
#' @param infected   Infectious-count census Column (`nodes$I`), `slice_len == n_nodes`.
#' @param population Per-node population census Column (`nodes$N`); the FOI denominator.
#' @param beta       Transmission-coefficient grid (`n_ticks x n_nodes`, from
#'   [values_map()]).
#' @param seasonality Seasonal-modifier grid (`n_ticks x n_nodes`, from [values_map()]).
#' @param network    An `n_nodes x n_nodes` numeric coupling matrix.
#' @param foi        A 2-D f64 Column (`(n_ticks-1) x n_nodes`); column `tick` is overwritten.
#' @param tick       0-based tick index: reads `beta[tick]`/`seasonality[tick]` and
#'   `infected[tick+1]`/`population[tick+1]`, writes `foi[tick]`.
#' @return `NULL` (invisibly); the result is written into `foi`.
#' @export
calc_foi <- function(infected, population, beta, seasonality, network, foi, tick) .Call(wrap__calc_foi, infected, population, beta, seasonality, network, foi, tick)

#' Transmission step for tick `tick`: move susceptibles into a receiving state.
#'
#' Converts column `tick` of `foi` (a rate) to a per-node per-tick infection
#' probability `p[k] = 1 - exp(-foi[k])` — computed ONCE per node, not per agent.
#' Then, for each of the first `count` susceptible (`S`) agents, with probability
#' `p[nodeid]` it moves the agent into `to_state` — `I` for an SIR model or `E` for
#' SEIR — drawing the agent's `timer` for that state from `duration` (rounded to
#' whole ticks, clamped to `[1, 255]`) and tallying the event for its node. The
#' timer is whatever clock the receiving state uses next (incubation for `E`,
#' infectious period for `I`); the caller passes the matching `timer` column and
#' `duration`. New infections per node are counted in parallel (private per-thread
#' buffers, summed at the end) and applied as a delta to column `tick + 1` of the
#' census (`S` down, the receiving state's `to_count` up; the caller has already
#' carried the census forward), and recorded in column `tick` of `incidence`.
#'
#' @param state      Per-agent `u8` state Column (mutated).
#' @param timer      Per-agent `u8` countdown Column for the receiving state (mutated).
#' @param nodeid     Per-agent `u16` 0-based node-id Column.
#' @param count      Number of active agents to process.
#' @param foi        `n_ticks x n_nodes` f64 FOI Column (from [calc_foi()]); column
#'   `tick` is read.
#' @param s_count    `n_ticks+1 × n_nodes` i32 census Column for `S` (mutated at `tick+1`).
#' @param to_count   `n_ticks+1 × n_nodes` i32 census Column for the receiving state
#'   `to_state` (mutated at `tick+1`).
#' @param incidence  `n_ticks x n_nodes` i32 flow Column (mutated at `tick`).
#' @param tick       0-based tick index.
#' @param to_state   State code new infections enter (e.g. `laser_states()[["I"]]`
#'   for SIR or `[["E"]]` for SEIR).
#' @param duration   A Distribution from which the receiving state's timer is drawn.
#' @return `NULL` (invisibly); the Columns are modified in place.
#' @export
transmission <- function(state, timer, nodeid, count, foi, s_count, to_count, incidence, tick, to_state, duration) .Call(wrap__transmission, state, timer, nodeid, count, foi, s_count, to_count, incidence, tick, to_state, duration)

#' Fixed-capacity struct-of-arrays population or patch data store.
#'
#' Mirrors `laser.core.LaserFrame` from Python. Each property occupies a
#' pre-allocated backing array; `count` tracks how many entries are active.
#'
#' **Scalar properties** store one value per entry (length = `capacity`).
#'
#' **Vector properties** store `length` values per entry, laid out column-major
#' so that `get_col(name, col)` returns a contiguous memory slice. This is
#' R's native matrix storage order and makes per-tick node-state updates fast.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Create a new `LaserFrame`.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`capacity`}{Maximum number of entries (agents or nodes). Must be positive.}
#'\item{`initial_count`}{Number of entries active at construction. Pass `-1` (the default) to set active count equal to `capacity`.}
#'}}
#' \subsection{return}{
#'A new `LaserFrame` object.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `count`}{
#'Number of currently active entries.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `capacity`}{
#'Total capacity (fixed at construction).
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `scalar_names`}{
#'Names of all scalar properties, sorted alphabetically.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `vector_names`}{
#'Names of all vector properties, sorted alphabetically.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `vector_ncols`}{
#'Number of columns in a named vector property.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `describe`}{
#'Human-readable summary of the frame's properties and memory layout.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `add_scalar_property`}{
#'Add a scalar property (one value per entry).
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Property name. Must not already exist.}
#'\item{`dtype`}{`"integer"`, `"real"`, or `"logical"`.}
#'\item{`default`}{Fill value for the backing array.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `add_vector_property`}{
#'Add a vector property (`capacity × length`, column-major).
#'
#'The backing array has `capacity * length` elements.
#'Element `[entry, col]` is stored at offset `entry + col * capacity`.
#'Column `col` (all active entries for one time-step) is contiguous.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Property name. Must not already exist.}
#'\item{`length`}{Number of columns (e.g., `nticks + 1` for a time-series).}
#'\item{`dtype`}{`"integer"`, `"real"`, or `"logical"`.}
#'\item{`default`}{Fill value.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `add`}{
#'Activate `n` additional entries and return their 1-based index range.
#'
#'Returns `c(start, end)` (both inclusive, 1-based) so that
#'`frame$get("prop")[start:end]` addresses the newly activated entries.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`n`}{Number of entries to activate.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `squash`}{
#'Compact active entries, keeping only those where `mask` is `TRUE`.
#'
#'All scalar and vector properties are squashed in place.
#'`count` is updated to the number of kept entries.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`mask`}{Logical vector of length `count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `sort_by`}{
#'Reorder active scalar properties by `perm` (1-based permutation of length `count`).
#'
#'Each property is permuted in parallel across available CPU threads via Rayon.
#'Only scalar properties are reordered; vector properties (time-series) are left unchanged.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`perm`}{Integer vector of length `count`. Must be a valid permutation of `1:count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `get`}{
#'Return the active slice of a scalar property as an R vector.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Scalar property name.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set`}{
#'Overwrite the active slice of a scalar property from an R vector.
#'
#'Integer and real vectors are accepted for integer and real properties
#'respectively; integer values are accepted for real properties (coerced).
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Scalar property name.}
#'\item{`values`}{R vector of length `count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `get_col`}{
#'Return one column of a vector property as an R vector.
#'
#'The column is returned for active entries only (length = `count`).
#'Columns are **1-based**: column 1 is the first column.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'\item{`col`}{Column index (1-based).}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set_col`}{
#'Overwrite one column of a vector property from an R vector.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'\item{`col`}{Column index (1-based).}
#'\item{`values`}{R vector of length `count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `get_matrix`}{
#'Return a vector property as an R matrix of shape `(count, ncols)`.
#'
#'Because both R and the backing store use column-major layout, each
#'column of the returned matrix is a direct contiguous copy.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
LaserFrame <- new.env(parent = emptyenv())

LaserFrame$new <- function(capacity, initial_count) .Call(wrap__LaserFrame__new, capacity, initial_count)

LaserFrame$count <- function() .Call(wrap__LaserFrame__count, self)

LaserFrame$capacity <- function() .Call(wrap__LaserFrame__capacity, self)

LaserFrame$scalar_names <- function() .Call(wrap__LaserFrame__scalar_names, self)

LaserFrame$vector_names <- function() .Call(wrap__LaserFrame__vector_names, self)

LaserFrame$vector_ncols <- function(name) .Call(wrap__LaserFrame__vector_ncols, self, name)

LaserFrame$describe <- function() .Call(wrap__LaserFrame__describe, self)

LaserFrame$add_scalar_property <- function(name, dtype, default) .Call(wrap__LaserFrame__add_scalar_property, self, name, dtype, default)

LaserFrame$add_vector_property <- function(name, length, dtype, default) .Call(wrap__LaserFrame__add_vector_property, self, name, length, dtype, default)

LaserFrame$add <- function(n) .Call(wrap__LaserFrame__add, self, n)

LaserFrame$squash <- function(mask) .Call(wrap__LaserFrame__squash, self, mask)

LaserFrame$sort_by <- function(perm) .Call(wrap__LaserFrame__sort_by, self, perm)

LaserFrame$get <- function(name) .Call(wrap__LaserFrame__get, self, name)

LaserFrame$set <- function(name, values) .Call(wrap__LaserFrame__set, self, name, values)

LaserFrame$get_col <- function(name, col) .Call(wrap__LaserFrame__get_col, self, name, col)

LaserFrame$set_col <- function(name, col, values) .Call(wrap__LaserFrame__set_col, self, name, col, values)

LaserFrame$get_matrix <- function(name) .Call(wrap__LaserFrame__get_matrix, self, name)

#' @rdname LaserFrame
#' @usage NULL
#' @export
`$.LaserFrame` <- function (self, name) { func <- LaserFrame[[name]]; environment(func) <- environment(); func }

#' @export
`[[.LaserFrame` <- `$.LaserFrame`

#' A parameterized probability distribution that can be sampled repeatedly.
#'
#' Build one with a family constructor such as `dist_normal()` or `dist_constant()`,
#' then either sample it from Rust via `sample()` (Pattern B: the caller owns the
#' RNG and passes it in), or from R via `$sample_one()` / `$sample_n()`.
#'
#' Draws are always floating-point. Callers that need integer values (e.g. a
#' whole-tick state timer) are responsible for rounding or truncating as
#' appropriate — the simulation kernels round to the nearest tick.
#'
#' The handle is opaque to R — it is passed to simulation kernels (e.g.
#' `step_exposed_ei`) by reference, so the same object can be reused every tick
#' and shared across all worker threads.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `sample_one`}{
#'Draw a single sample using a thread-local RNG.
#'
#'Convenience for interactive use. Simulation kernels do not call this — they
#'use the internal sampler with an explicit, reusable RNG for performance.
#'
#' \subsection{return}{
#'A single numeric (double) draw from the distribution.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `sample_n`}{
#'Draw `n` samples using a thread-local RNG, returned as a numeric vector.
#'
#'Drawing a whole batch in one call avoids per-sample R↔Rust overhead, which
#'makes it practical to validate the sampler against large empirical samples
#'(e.g. one million draws) from R.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`n`}{Number of samples to draw; must be non-negative.}
#'}}
#' \subsection{return}{
#'A numeric (double) vector of length `n`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
Distribution <- new.env(parent = emptyenv())

Distribution$sample_one <- function() .Call(wrap__Distribution__sample_one, self)

Distribution$sample_n <- function(n) .Call(wrap__Distribution__sample_n, self, n)

#' @rdname Distribution
#' @usage NULL
#' @export
`$.Distribution` <- function (self, name) { func <- Distribution[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Distribution` <- `$.Distribution`

#' A Rust-owned, dtype-tagged property array (1-D scalar, or a 2-D vector report).
#'
#' Allocate one with [allocate_scalar()] (`nrows` elements, `ncols == 1`) or
#' [allocate_vector()] (`nrows`-per-slot × `ncols` slots, stored COLUMN-MAJOR so a
#' whole slot/time-slice is contiguous). The data is held in Rust and exposed to
#' R only as an opaque handle; use `$values()` to copy a snapshot back into an R
#' vector (or matrix, when `ncols > 1`) for inspection, `$fill()` / `$set()` to
#' write, and `$length()` / `$dtype()` to query. The simulation step kernels
#' operate on the buffer in place with no copies.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `length`}{
#'Number of elements in the array.
#' \subsection{return}{
#'An integer length.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `dtype`}{
#'The element data type as a string (e.g. `"u8"`, `"f32"`).
#' \subsection{return}{
#'A length-1 character vector.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `values`}{
#'Copy the array into an R vector for inspection (NOT a view — a snapshot).
#'
#'Integer-width types (i8, u8, i16, u16, i32) widen to R `integer`; `u32`,
#'`f32`, and `f64` widen to R `double` (since `u32` overflows R's signed
#'32-bit integer). This O(n) copy is the only place data leaves Rust.
#'
#'For a 2-D column (`n_slices > 1`, from [allocate_vector()]) the result carries
#'a `dim` attribute and reads back as an `n_slices × slice_len` R matrix (e.g.
#'`n_ticks × n_nodes`), so row `t` is tick `t`'s per-node vector; otherwise a
#'plain vector. The snapshot is transposed during the copy (our buffer is
#'slice-major, R matrices are column-major) — inexpensive, inspection-only.
#'
#' \subsection{return}{
#'A numeric vector (or matrix) — integer or double — of `length()` elements.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `fill`}{
#'Set every element to `value`, cast to the array's data type.
#'
#'For integer-typed arrays the value is truncated toward zero (e.g. `2.9`
#'becomes `2`); out-of-range values wrap per Rust's `as` cast.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`value`}{A single numeric value to broadcast across the array.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set`}{
#'Overwrite the array from an R numeric vector (integer or double).
#'
#'The input length must equal `length()`. Each element is cast to the array's
#'data type (integer-typed arrays truncate toward zero). Useful for setup —
#'e.g. writing per-agent node assignments or seeding initial states from R.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`values`}{A numeric vector of length `length()`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
Column <- new.env(parent = emptyenv())

Column$length <- function() .Call(wrap__Column__length, self)

Column$dtype <- function() .Call(wrap__Column__dtype, self)

Column$values <- function() .Call(wrap__Column__values, self)

Column$fill <- function(value) .Call(wrap__Column__fill, self, value)

Column$set <- function(values) .Call(wrap__Column__set, self, values)

#' @rdname Column
#' @usage NULL
#' @export
`$.Column` <- function (self, name) { func <- Column[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Column` <- `$.Column`

# nolint end
