# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib razer, .registration = TRUE
NULL

#' Named integer vector of epidemic compartment state codes.
#'
#' Returns `c(S=0L, E=1L, I=2L, R=3L, D=-1L)`. Use these constants to set
#' and test the `state` property on a people frame.
#'
#' @return Named integer vector with elements S, E, I, R, D.
#' @export
laser_states <- function() .Call(wrap__laser_states)

#' Stochastic S→I transmission step (SI / SIR kernel).
#'
#' **Parallelism:** the active agent array is split into fixed chunks — one per
#' Rayon worker thread — matching the `prange` pattern. The aggregation phase
#' uses a thread-local fold then reduces by element-wise summation. The FOI
#' phase runs each chunk independently; RNG is thread-local (`rand::thread_rng()`).
#'
#' All operations are performed in-place on the backing arrays; no copies are made.
#'
#' Node-level I counts are computed from current agent states and written to
#' `nodes$I` (overwriting the previous value).
#'
#' **Required people properties:** `state` (integer), `node` (integer, 0-based),
#' `timer` (integer).
#' **Required nodes properties:** `N` (integer, total population per node),
#' `I` (integer, will be overwritten).
#'
#' @param people       LaserFrame of agents.
#' @param nodes        LaserFrame of patches/nodes.
#' @param beta         Transmission rate (force of infection per infectious contact per tick).
#' @param inf_dist     A `Distribution` (e.g. `dist_constant()` or `dist_normal()`) giving the
#'   infectious period in ticks; sampled per newly infected agent and written to
#'   `timer` on S→I (rounded to whole ticks, clamped to a minimum of 1).
#' @export
step_transmission_si <- function(people, nodes, beta, inf_dist) .Call(wrap__step_transmission_si, people, nodes, beta, inf_dist)

#' Stochastic S→E exposure step (SEIR kernel).
#'
#' Same FOI computation and parallelism as `step_transmission_si`, but newly
#' exposed agents move to state E and `timer` is set to a draw from `exp_dist`
#' (incubation period). Pair with `step_exposed_ei` to complete E→I.
#'
#' **Required people properties:** `state`, `node`, `timer` (all integer).
#' **Required nodes properties:** `N`, `I` (integer; `I` is overwritten).
#'
#' @param people        LaserFrame of agents.
#' @param nodes         LaserFrame of patches/nodes.
#' @param beta          Transmission rate.
#' @param exp_dist      A `Distribution` (e.g. `dist_constant()` or `dist_normal()`) giving the
#'   incubation period in ticks; sampled per newly exposed agent and written to
#'   `timer` on S→E (rounded to whole ticks, clamped to a minimum of 1).
#' @export
step_transmission_se <- function(people, nodes, beta, exp_dist) .Call(wrap__step_transmission_se, people, nodes, beta, exp_dist)

#' Generalized timer-expiry transition into an *absorbing* (untimed) state.
#'
#' For each agent currently in `from_state`, decrements `timer` by 1; when the
#' timer reaches 0 the agent moves to `to_state` and its timer is left at 0. The
#' destination carries no duration of its own — this is the "transition to an
#' absorbing state" generalization (laser-generic's `nb_timer_update`), e.g.
#' I→S in SIS, I→R in SIR, or R→S waning.
#'
#' This is the engine behind [step_infectious_is()] (I→S) and
#' [step_recovered_rs()] (R→S):
#' `step_timer_expire(people, laser_states()[["I"]], laser_states()[["S"]])`
#' is exactly `step_infectious_is(people)`.
#'
#' **Required people properties:** `state`, `timer` (both integer).
#'
#' @param people     LaserFrame of agents.
#' @param from_state Integer state code an agent must currently occupy to be eligible.
#' @param to_state   Integer state code an agent moves to when its timer expires.
#' @export
step_timer_expire <- function(people, from_state, to_state) .Call(wrap__step_timer_expire, people, from_state, to_state)

#' Generalized timer-expiry transition into a state that has *its own* duration.
#'
#' For each agent currently in `from_state`, decrements `timer` by 1; when the
#' timer reaches 0 the agent moves to `to_state` and `timer` is reset to a fresh
#' per-agent draw from `duration_dist` (rounded to whole ticks, clamped to a
#' minimum of 1). This is the "transition to a state with its own duration timer"
#' generalization (laser-generic's `nb_timer_update_timer_set`), e.g. E→I in
#' SEIR or I→R with waning in SEIRS.
#'
#' This is the engine behind [step_exposed_ei()] (E→I) and
#' [step_infectious_ir()] (I→R):
#' `step_timer_expire_set(people, laser_states()[["E"]], laser_states()[["I"]], inf_dist)`
#' is exactly `step_exposed_ei(people, inf_dist)`.
#'
#' **RNG:** thread-local (Pattern B) — each Rayon worker draws from its own
#' `thread_rng`; the single `duration_dist` handle is shared across threads by
#' reference.
#'
#' **Required people properties:** `state`, `timer` (both integer).
#'
#' @param people        LaserFrame of agents.
#' @param from_state    Integer state code an agent must currently occupy to be eligible.
#' @param to_state      Integer state code an agent moves to when its timer expires.
#' @param duration_dist A `Distribution` (e.g. `dist_constant()` or `dist_normal()`)
#'   giving the destination state's duration in ticks; sampled per transitioning
#'   agent and written to `timer`.
#' @export
step_timer_expire_set <- function(people, from_state, to_state, duration_dist) .Call(wrap__step_timer_expire_set, people, from_state, to_state, duration_dist)

#' Timer-based E→I transition (SEIR kernel).
#'
#' For each exposed agent, decrements `timer` by 1. When `timer` reaches 0 the
#' agent transitions to state I and `timer` is set to a fresh draw from
#' `inf_dist`, the infectious-period distribution. Pass `dist_constant(d)` for a
#' fixed period of `d` ticks, or e.g. `dist_normal(mean, variance)` for a stochastic
#' per-agent period. Draws are rounded to the nearest tick and clamped to a
#' minimum of 1.
#'
#' A fixed-state shorthand for
#' [step_timer_expire_set()]`(people, E, I, inf_dist)`.
#'
#' **RNG:** thread-local — each Rayon worker draws from its own `thread_rng`
#' (Pattern B: the kernel owns the RNG and passes it into the sampler). The
#' single `inf_dist` handle is shared across threads by reference.
#'
#' @param people    LaserFrame of agents.
#' @param inf_dist  A `Distribution` (e.g. from `dist_constant()` or `dist_normal()`)
#'   giving the infectious period in ticks; sampled and written to `timer` on E→I.
#' @export
step_exposed_ei <- function(people, inf_dist) .Call(wrap__step_exposed_ei, people, inf_dist)

#' Timer-based I→R transition (SIR / SEIR / SEIRS kernel).
#'
#' For each infectious agent, decrements `timer` by 1. When `timer` reaches 0
#' the agent transitions to state R and `timer` is set to a draw from `imm_dist`,
#' the immunity (waning) period.
#'
#' A fixed-state shorthand for
#' [step_timer_expire_set()]`(people, I, R, imm_dist)`.
#'
#' For SEIRS, pass the desired immunity distribution so that `step_recovered_rs`
#' counts down R→S from a fresh per-agent draw. For SIR and SEIR (no waning,
#' `step_recovered_rs` never called) the R timer is never read, so any
#' distribution works — `dist_constant(0)` is the conventional "don't care".
#'
#' **RNG:** thread-local — each Rayon worker draws from its own `thread_rng`
#' (Pattern B). The single `imm_dist` handle is shared across threads by reference.
#'
#' @param people    LaserFrame of agents.
#' @param imm_dist  A `Distribution` (e.g. `dist_constant()` or `dist_normal()`) giving the
#'   immunity period in ticks; sampled and written to `timer` on I→R (rounded to
#'   whole ticks, clamped to a minimum of 1). Use `dist_constant(0)` for SIR / SEIR.
#' @export
step_infectious_ir <- function(people, imm_dist) .Call(wrap__step_infectious_ir, people, imm_dist)

#' Timer-based I→S transition for SIS models (no immunity).
#'
#' For each infectious agent, decrements `timer` by 1. When `timer` reaches 0
#' the agent transitions directly back to state S.
#'
#' A fixed-state shorthand for [step_timer_expire()]`(people, I, S)`.
#'
#' @param people LaserFrame of agents.
#' @export
step_infectious_is <- function(people) .Call(wrap__step_infectious_is, people)

#' Timer-based R→S transition for waning-immunity models.
#'
#' For each recovered agent, decrements `timer` by 1. When `timer` reaches 0
#' the agent becomes susceptible again (state S).
#'
#' A fixed-state shorthand for [step_timer_expire()]`(people, R, S)`.
#'
#' @param people LaserFrame of agents.
#' @export
step_recovered_rs <- function(people) .Call(wrap__step_recovered_rs, people)

#' Stochastic mortality step using a crude death rate.
#'
#' For each living (non-D) agent, draws Bernoulli(`cdr`) for death.
#' Agents that die have their state set to D (-1) and `timer` set to 0.
#' Dead agents remain in the frame — call `$squash(people$state >= 0L)`
#' periodically to compact.
#'
#' Each agent's draw is independent; Rayon assigns a fixed slice to each worker
#' thread. RNG is thread-local (no locking).
#'
#' @param people LaserFrame of agents.
#' @param cdr    Crude death rate per agent per tick (probability in \[0, 1\]).
#' @export
step_mortality_cdr <- function(people, cdr) .Call(wrap__step_mortality_cdr, people, cdr)

#' Stochastic birth step using a crude birth rate.
#'
#' **Parallelism:** the Bernoulli draw (does this agent give birth?) is
#' parallelised across all active agents. The subsequent bookkeeping —
#' incrementing `count` and writing new-agent properties — is serial because
#' it modifies the frame's active count.
#'
#' For each active (non-D) agent, draws Bernoulli(`cbr`) for a birth event.
#' Each birth creates one new agent that inherits the parent's `node` and
#' starts in state S with `timer = 0`. Other scalar properties of new agents
#' take the default value set at `add_scalar_property` time.
#'
#' Excess births beyond `capacity - count` are silently dropped.
#'
#' **Required people properties:** `state`, `node`, `timer` (all integer).
#'
#' @param people LaserFrame of agents.
#' @param cbr    Crude birth rate per agent per tick (probability in \[0, 1\]).
#' @export
step_births_cbr <- function(people, cbr) .Call(wrap__step_births_cbr, people, cbr)

#' Create a normal (Gaussian) distribution.
#'
#' The second argument is the **variance** (σ²), not the standard deviation, to
#' match the way variance is usually quoted in statistical models. The standard
#' deviation passed to the underlying sampler is `sqrt(variance)`.
#'
#' @param mean      Mean (μ) of the distribution.
#' @param variance  Variance (σ²); must be non-negative.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_normal(7, 4)   # mean 7, variance 4 (sd 2)
#' d$sample_one()
#' @export
dist_normal <- function(mean, variance) .Call(wrap__dist_normal, mean, variance)

#' Create a degenerate (constant) distribution that always returns `value`.
#'
#' Use this as a fixed-duration drop-in wherever a `Distribution` is required —
#' e.g. a deterministic infectious period of exactly `value` ticks.
#'
#' @param value The constant value returned by every draw.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_constant(10)   # always 10
#' d$sample_one()
#' @export
dist_constant <- function(value) .Call(wrap__dist_constant, value)

#' Create a continuous uniform distribution on the half-open interval [low, high).
#'
#' Every value in `[low, high)` is equally likely. The mean is `(low + high) / 2`.
#'
#' @param low   Inclusive lower bound.
#' @param high  Exclusive upper bound; must be strictly greater than `low`.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_uniform(3, 8)   # values in [3, 8), mean 5.5
#' d$sample_one()
#' @export
dist_uniform <- function(low, high) .Call(wrap__dist_uniform, low, high)

#' Create a gamma distribution parameterized by shape and scale.
#'
#' Uses the shape–scale (k, θ) parameterization: the mean is `shape * scale` and
#' the variance is `shape * scale^2`. Draws are strictly positive, which makes the
#' gamma a natural choice for right-skewed, always-positive durations.
#'
#' @param shape  Shape parameter k; must be finite and positive.
#' @param scale  Scale parameter θ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_gamma(2, 3)   # mean 6, variance 18
#' d$sample_one()
#' @export
dist_gamma <- function(shape, scale) .Call(wrap__dist_gamma, shape, scale)

#' Create a Poisson distribution with rate (mean) `lambda`.
#'
#' Draws are non-negative integer counts (returned as doubles) with mean and
#' variance both equal to `lambda`. Useful for count-valued durations.
#'
#' @param lambda  Rate / mean λ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_poisson(5)   # mean 5, integer-valued draws
#' d$sample_one()
#' @export
dist_poisson <- function(lambda) .Call(wrap__dist_poisson, lambda)

#' Create a beta distribution on the open interval (0, 1).
#'
#' Parameterized by the two positive shape parameters α and β. The mean is
#' `alpha / (alpha + beta)`.
#'
#' @param alpha  First shape parameter (α); must be finite and positive.
#' @param beta   Second shape parameter (β); must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_beta(2, 5)   # mean 2/7 ≈ 0.286, support (0, 1)
#' d$sample_one()
#' @export
dist_beta <- function(alpha, beta) .Call(wrap__dist_beta, alpha, beta)

#' Create an exponential distribution with rate `rate`.
#'
#' Draws are strictly positive with mean `1 / rate` and variance `1 / rate^2`.
#'
#' @param rate  Rate parameter λ; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_exp(0.5)   # mean 2
#' d$sample_one()
#' @export
dist_exp <- function(rate) .Call(wrap__dist_exp, rate)

#' Create a logistic distribution with the given location and scale.
#'
#' Symmetric about `location` (its mean and median); the variance is
#' `scale^2 * pi^2 / 3`.
#'
#' @param location  Location parameter μ (the mean); must be finite.
#' @param scale     Scale parameter s; must be finite and positive.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_logistic(4, 2)   # mean 4
#' d$sample_one()
#' @export
dist_logistic <- function(location, scale) .Call(wrap__dist_logistic, location, scale)

#' Create a log-normal distribution.
#'
#' A variable whose natural logarithm is `Normal(meanlog, sdlog)`. Draws are
#' strictly positive. The median is `exp(meanlog)` and the mean is
#' `exp(meanlog + sdlog^2 / 2)`. `meanlog` and `sdlog` are the log-space
#' parameters, matching R's `qlnorm(p, meanlog, sdlog)`.
#'
#' @param meanlog  Mean of the underlying normal (in log space); must be finite.
#' @param sdlog    Standard deviation of the underlying normal; must be finite
#'   and non-negative.
#' @return A `Distribution` object.
#' @examples
#' d <- dist_lognormal(0, 0.5)   # median 1
#' d$sample_one()
#' @export
dist_lognormal <- function(meanlog, sdlog) .Call(wrap__dist_lognormal, meanlog, sdlog)

#' Fixed-capacity struct-of-arrays population or patch data store.
#'
#' Mirrors `laser.core.LaserFrame` from Python. Each property occupies a
#' pre-allocated backing array; `count` tracks how many entries are active.
#'
#' **Scalar properties** store one value per entry (length = `capacity`).
#'
#' **Vector properties** store `length` values per entry, laid out column-major
#' so that `get_col(name, col)` returns a contiguous memory slice. This is
#' R's native matrix storage order and makes per-tick node-state updates fast.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `new`}{
#'Create a new `LaserFrame`.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`capacity`}{Maximum number of entries (agents or nodes). Must be positive.}
#'\item{`initial_count`}{Number of entries active at construction. Pass `-1` (the default) to set active count equal to `capacity`.}
#'}}
#' \subsection{return}{
#'A new `LaserFrame` object.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `count`}{
#'Number of currently active entries.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `capacity`}{
#'Total capacity (fixed at construction).
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `scalar_names`}{
#'Names of all scalar properties, sorted alphabetically.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `vector_names`}{
#'Names of all vector properties, sorted alphabetically.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `vector_ncols`}{
#'Number of columns in a named vector property.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `describe`}{
#'Human-readable summary of the frame's properties and memory layout.
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `add_scalar_property`}{
#'Add a scalar property (one value per entry).
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Property name. Must not already exist.}
#'\item{`dtype`}{`"integer"`, `"real"`, or `"logical"`.}
#'\item{`default`}{Fill value for the backing array.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `add_vector_property`}{
#'Add a vector property (`capacity × length`, column-major).
#'
#'The backing array has `capacity * length` elements.
#'Element `[entry, col]` is stored at offset `entry + col * capacity`.
#'Column `col` (all active entries for one time-step) is contiguous.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Property name. Must not already exist.}
#'\item{`length`}{Number of columns (e.g., `nticks + 1` for a time-series).}
#'\item{`dtype`}{`"integer"`, `"real"`, or `"logical"`.}
#'\item{`default`}{Fill value.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `add`}{
#'Activate `n` additional entries and return their 1-based index range.
#'
#'Returns `c(start, end)` (both inclusive, 1-based) so that
#'`frame$get("prop")[start:end]` addresses the newly activated entries.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`n`}{Number of entries to activate.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `squash`}{
#'Compact active entries, keeping only those where `mask` is `TRUE`.
#'
#'All scalar and vector properties are squashed in place.
#'`count` is updated to the number of kept entries.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`mask`}{Logical vector of length `count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `sort_by`}{
#'Reorder active scalar properties by `perm` (1-based permutation of length `count`).
#'
#'Each property is permuted in parallel across available CPU threads via Rayon.
#'Only scalar properties are reordered; vector properties (time-series) are left unchanged.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`perm`}{Integer vector of length `count`. Must be a valid permutation of `1:count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `get`}{
#'Return the active slice of a scalar property as an R vector.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Scalar property name.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set`}{
#'Overwrite the active slice of a scalar property from an R vector.
#'
#'Integer and real vectors are accepted for integer and real properties
#'respectively; integer values are accepted for real properties (coerced).
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Scalar property name.}
#'\item{`values`}{R vector of length `count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `get_col`}{
#'Return one column of a vector property as an R vector.
#'
#'The column is returned for active entries only (length = `count`).
#'Columns are **1-based**: column 1 is the first column.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'\item{`col`}{Column index (1-based).}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `set_col`}{
#'Overwrite one column of a vector property from an R vector.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'\item{`col`}{Column index (1-based).}
#'\item{`values`}{R vector of length `count`.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `get_matrix`}{
#'Return a vector property as an R matrix of shape `(count, ncols)`.
#'
#'Because both R and the backing store use column-major layout, each
#'column of the returned matrix is a direct contiguous copy.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`name`}{Vector property name.}
#'}}
#' \subsection{export}{
#'
#'}
#'}
#'
LaserFrame <- new.env(parent = emptyenv())

LaserFrame$new <- function(capacity, initial_count) .Call(wrap__LaserFrame__new, capacity, initial_count)

LaserFrame$count <- function() .Call(wrap__LaserFrame__count, self)

LaserFrame$capacity <- function() .Call(wrap__LaserFrame__capacity, self)

LaserFrame$scalar_names <- function() .Call(wrap__LaserFrame__scalar_names, self)

LaserFrame$vector_names <- function() .Call(wrap__LaserFrame__vector_names, self)

LaserFrame$vector_ncols <- function(name) .Call(wrap__LaserFrame__vector_ncols, self, name)

LaserFrame$describe <- function() .Call(wrap__LaserFrame__describe, self)

LaserFrame$add_scalar_property <- function(name, dtype, default) .Call(wrap__LaserFrame__add_scalar_property, self, name, dtype, default)

LaserFrame$add_vector_property <- function(name, length, dtype, default) .Call(wrap__LaserFrame__add_vector_property, self, name, length, dtype, default)

LaserFrame$add <- function(n) .Call(wrap__LaserFrame__add, self, n)

LaserFrame$squash <- function(mask) .Call(wrap__LaserFrame__squash, self, mask)

LaserFrame$sort_by <- function(perm) .Call(wrap__LaserFrame__sort_by, self, perm)

LaserFrame$get <- function(name) .Call(wrap__LaserFrame__get, self, name)

LaserFrame$set <- function(name, values) .Call(wrap__LaserFrame__set, self, name, values)

LaserFrame$get_col <- function(name, col) .Call(wrap__LaserFrame__get_col, self, name, col)

LaserFrame$set_col <- function(name, col, values) .Call(wrap__LaserFrame__set_col, self, name, col, values)

LaserFrame$get_matrix <- function(name) .Call(wrap__LaserFrame__get_matrix, self, name)

#' @rdname LaserFrame
#' @usage NULL
#' @export
`$.LaserFrame` <- function (self, name) { func <- LaserFrame[[name]]; environment(func) <- environment(); func }

#' @export
`[[.LaserFrame` <- `$.LaserFrame`

#' A parameterized probability distribution that can be sampled repeatedly.
#'
#' Build one with a family constructor such as `dist_normal()` or `dist_constant()`,
#' then either sample it from Rust via `sample()` (Pattern B: the caller owns the
#' RNG and passes it in), or from R via `$sample_one()` / `$sample_n()`.
#'
#' Draws are always floating-point. Callers that need integer values (e.g. a
#' whole-tick state timer) are responsible for rounding or truncating as
#' appropriate — the simulation kernels round to the nearest tick.
#'
#' The handle is opaque to R — it is passed to simulation kernels (e.g.
#' `step_exposed_ei`) by reference, so the same object can be reused every tick
#' and shared across all worker threads.
#'
#' @export
#'
#' @section Methods:
#'\subsection{Method `sample_one`}{
#'Draw a single sample using a thread-local RNG.
#'
#'Convenience for interactive use. Simulation kernels do not call this — they
#'use the internal sampler with an explicit, reusable RNG for performance.
#'
#' \subsection{return}{
#'A single numeric (double) draw from the distribution.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
#'\subsection{Method `sample_n`}{
#'Draw `n` samples using a thread-local RNG, returned as a numeric vector.
#'
#'Drawing a whole batch in one call avoids per-sample R↔Rust overhead, which
#'makes it practical to validate the sampler against large empirical samples
#'(e.g. one million draws) from R.
#'
#' \subsection{Arguments}{
#'\describe{
#'\item{`n`}{Number of samples to draw; must be non-negative.}
#'}}
#' \subsection{return}{
#'A numeric (double) vector of length `n`.
#'}
#' \subsection{export}{
#'
#'}
#'}
#'
Distribution <- new.env(parent = emptyenv())

Distribution$sample_one <- function() .Call(wrap__Distribution__sample_one, self)

Distribution$sample_n <- function(n) .Call(wrap__Distribution__sample_n, self, n)

#' @rdname Distribution
#' @usage NULL
#' @export
`$.Distribution` <- function (self, name) { func <- Distribution[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Distribution` <- `$.Distribution`

# nolint end
